### ISSUE TITLE
[BUG] cant have enums in responses

### ISSUE THREAD

**Issue by angusmunro** [TypedProject/ts-express-decorators#1446]
## Information

- **Version:** 6.59.0
- Packages: @tsed/common, @tsed/schema

If I have a response model in a controller where the type is set to an enum it causes a maximum call stack size exceeded when endpoint is hit. Current workaround is to have properties as strings instead of enums.

## Example

```
import { Controller, Get } from '@tsed/common';
import { Description, Enum, Example, Required, Returns, Summary, Title } from '@tsed/schema';

export enum ExampleEnum {
  one = 'one',
  two = 'two',
}

export class ExampleResponse {
  @Title('title')
  @Description('description')
  @Example(ExampleEnum.one)
  @Enum(ExampleEnum)
  @Required()
  example: ExampleEnum; // TODO: Why cant I set this to enum?
  // example: string; // this works 
}

@Controller({
  path: '/example',
  children: [
  ],
})
export class ExampleController {
  @Returns(200, ExampleResponse).Description('Successful example Response')
  @Summary('Example endpoint')
  @Get('/')
  public async getExample(
  ): Promise<ExampleResponse> {
    return {
      example: ExampleEnum.one,
    };
  }
}
```

## Acceptance criteria

- [ ] I should be able to set properties to have a typescript enum.

## Example error
```
RangeError: Maximum call stack size exceeded
        at Object.get [as isFunction] (/Users/XXX/source/XXX/XXX/node_modules/@tsed/core/node_modules/tslib/tslib.js:155:71)
        at Object.get [as isFunction] (/Users/XXX/source/XXX/XXX/node_modules/@tsed/core/node_modules/tslib/tslib.js:155:84)
        at Object.get [as isFunction] (/Users/XXX/source/XXX/XXX/node_modules/@tsed/core/node_modules/tslib/tslib.js:155:84)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:52:53
        at Array.filter (<anonymous>)
        at getObjectProperties (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:52:30)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:10)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
        at toObject (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:98:35)
        at serialize (/Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:155:68)
        at /Users/XXX/source/XXX/XXX/node_modules/@tsed/json-mapper/src/utils/serialize.ts:101:14
        at Array.reduce (<anonymous>)
```

**Comment by jappyjan** [comment]
same for me

**Comment by Romakita** [comment]
The example is not correct for me:

```
export class ExampleController {
  @Returns(200, ExampleResponse).Description('Successful example Response')
  @Summary('Example endpoint')
  @Get('/')
  public async getExample(
  ): Promise<ExampleResponse> {
    return { // isn't an instance of ExampleResponse
      example: ExampleEnum.one
    };
  }
}
```

**Comment by Romakita** [comment]
Hello @jappyjan,

I added unit test to cover you usecase. There is no error. See: https://github.com/tsedio/tsed/pull/1452

Can you produce a repository with reproducible example please?

See you,
Romain

**Comment by angusmunro** [comment]
I've tried to reproduce the issue on the latest version of tsed and it seems to work now... I'll reopen the issue with a full example repository if we encounter it again.

Thanks as always!
