### ISSUE TITLE
[BUG] Error: Cannot find module '../domain/JsonEntityStore'

### ISSUE THREAD

**Issue by paulg-mscience** [TypedProject/ts-express-decorators#1473]
## Information

- **Version:** 6.61.0
- Packages: 
     "@tsed/ajv": "6.61.0",
    "@tsed/common": "6.61.0",
    "@tsed/core": "6.61.0",
    "@tsed/di": "6.61.0",
    "@tsed/exceptions": "6.61.0",
    "@tsed/json-mapper": "6.61.0",
    "@tsed/platform-koa": "6.61.0",
    "@tsed/schema": "6.61.0",

Server fails to start with following call stack.

[2021-07-26T20:55:52.272] [ERROR] [TSED] - Error: Cannot find module '../domain/JsonEntityStore'
Require stack:
- /home/ec2-user/github/moo/node_modules/@tsed/schema/lib/index.js
- /home/ec2-user/github/moo/node_modules/@tsed/common/lib/mvc/models/EndpointMetadata.js
- /home/ec2-user/github/moo/node_modules/@tsed/common/lib/mvc/index.js
- /home/ec2-user/github/moo/node_modules/@tsed/common/lib/index.js
- /home/ec2-user/github/moo/src/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename (/home/ec2-user/github/moo/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at getJsonEntityStore (/home/ec2-user/github/moo/node_modules/@tsed/schema/src/utils/getJsonEntityStore.ts:7:10)
    at Object.getOperationsStores (/home/ec2-user/github/moo/node_modules/@tsed/schema/src/utils/getOperationsStores.ts:10:48)
    at Function.getEndpoints (/home/ec2-user/github/moo/node_modules/@tsed/common/src/mvc/models/EndpointMetadata.ts:126:24)
    at ControllerProvider.get endpoints [as endpoints] (/home/ec2-user/github/moo/node_modules/@tsed/common/src/platform/domain/ControllerProvider.ts:35:29)
    at PlatformControllerBuilder.buildEndpoints (/home/ec2-user/github/moo/node_modules/@tsed/common/src/platform/builder/PlatformControllerBuilder.ts:46:12) {
  name: 'INJECTION_ERROR',
  tokens: [ [class PlatformModule] ],
  origin: Error: Cannot find module '../domain/JsonEntityStore'
  Require stack:
  - /home/ec2-user/github/moo/node_modules/@tsed/schema/lib/index.js
  - /home/ec2-user/github/moo/node_modules/@tsed/common/lib/mvc/models/EndpointMetadata.js
  - /home/ec2-user/github/moo/node_modules/@tsed/common/lib/mvc/index.js
  - /home/ec2-user/github/moo/node_modules/@tsed/common/lib/index.js
  - /home/ec2-user/github/moo/src/index.ts
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
      at Function.Module._resolveFilename (/home/ec2-user/github/moo/node_modules/tsconfig-paths/lib/register.js:75:40)
      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at getJsonEntityStore (/home/ec2-user/github/moo/node_modules/@tsed/schema/src/utils/getJsonEntityStore.ts:7:10)
      at Object.getOperationsStores (/home/ec2-user/github/moo/node_modules/@tsed/schema/src/utils/getOperationsStores.ts:10:48)
      at Function.getEndpoints (/home/ec2-user/github/moo/node_modules/@tsed/common/src/mvc/models/EndpointMetadata.ts:126:24)
      at ControllerProvider.get endpoints [as endpoints] (/home/ec2-user/github/moo/node_modules/@tsed/common/src/platform/domain/ControllerProvider.ts:35:29)
      at PlatformControllerBuilder.buildEndpoints (/home/ec2-user/github/moo/node_modules/@tsed/common/src/platform/builder/PlatformControllerBuilder.ts:46:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/ec2-user/github/moo/node_modules/@tsed/schema/lib/index.js',
      '/home/ec2-user/github/moo/node_modules/@tsed/common/lib/mvc/models/EndpointMetadata.js',
      '/home/ec2-user/github/moo/node_modules/@tsed/common/lib/mvc/index.js',
      '/home/ec2-user/github/moo/node_modules/@tsed/common/lib/index.js',
      '/home/ec2-user/github/moo/src/index.ts'
    ]
  }
}

## Example

Build yourself a new server with following commands. 

```
npm install -g @tsed/cli
tsed init .
```
Upon `npm start` you will receive error. Revert to version 6.60.2 and server starts successfully.

## Acceptance criteria

- [ ] Newly scaffolded server should start successfully

**Comment by paulg-mscience** [comment]
@Romakita Thank you!

**Comment by Romakita** [comment]
@paulg-mscience The release is in progress ;)

**Comment by paulg-mscience** [comment]
Thanks. I will give the new release a try tomorrow. Cheers.

**Comment by paulg-mscience** [comment]
All looks good with v6.61.1. Thanks again. Ts.ED is great :)
