### ISSUE TITLE
[BUG] Enum on nested class causes stack loop error when serialized

### ISSUE THREAD

**Issue by ljonathanl** [TypedProject/ts-express-decorators#1534]
## Information

- **Version:** 6.64.1

I try to use an enum property on my nested model and I have a "RangeError: Maximum call stack size exceeded" when I serialize it. I don't have error when the enum property is just plain text not a type.

## Example

My model:

```typescript
import { Enum, Property, Required } from "@tsed/schema";

export enum EnumValue {
  One = "one",
  Two = "two",
}

export class NestedEnum {
  @Required()
  @Enum(EnumValue)
  value: EnumValue;
}

export class TestNestedEnum {
  @Property()
  nested: NestedEnum;
}

export class NestedEnum2 {
  @Required()
  @Enum("one", "two")
  value: "one" | "two";
}

export class TestNestedEnum2 {
  @Property()
  nested: NestedEnum2;
}

```

My controller:

```typescript
import {Controller, Get} from "@tsed/common";
import {Tags} from "@tsed/schema";
import { EnumValue, NestedEnum, TestNestedEnum, NestedEnum2, TestNestedEnum2 } from "../models/TestNestEnum";

@Controller("/enum")
@Tags("enum")
export class TestEnumController {
  @Get("/bug")
  async getBug(): Promise<TestNestedEnum> {
    const test = new TestNestedEnum();
    const nested = new NestedEnum();
    nested.value = EnumValue.One;
    test.nested = nested;
    return test;
  }

  @Get("/ok")
  async getOK(): Promise<TestNestedEnum2> {
    const test = new TestNestedEnum2();
    const nested = new NestedEnum2();
    nested.value = EnumValue.One;
    test.nested = nested;
    return test;
  }
}

```

If I call /enum/ok no problem, but /enum/bug throws this error when the model is serialized:

```
[ERROR] [TSED] - RangeError: Maximum call stack size exceeded
    at serialize (...\node_modules\@tsed\json-mapper\src\utils\serialize.ts:132:23)
    at ...\node_modules\@tsed\json-mapper\src\utils\serialize.ts:100:14
    at Array.reduce (<anonymous>)
    at toObject (...\node_modules\@tsed\json-mapper\src\utils\serialize.ts:97:35)
    at serialize (...\node_modules\@tsed\json-mapper\src\utils\serialize.ts:154:68)
    at ...\node_modules\@tsed\json-mapper\src\utils\serialize.ts:100:14
    at Array.reduce (<anonymous>)
...
```

## Acceptance criteria

- A nested enum can be serialized

**Comment by Romakita** [comment]
Can you try this example please:
```typescript
import {Controller, Get} from "@tsed/common";
import {Tags} from "@tsed/schema";
import { EnumValue, NestedEnum, TestNestedEnum, NestedEnum2, TestNestedEnum2 } from "../models/TestNestEnum";

@Controller("/enum")
@Tags("enum")
export class TestEnumController {
  @Get("/bug")
  @Returns(200, TestNestedEnum) // add this
  async getBug(): Promise<TestNestedEnum> {
    const test = new TestNestedEnum();
    const nested = new NestedEnum();
    nested.value = EnumValue.One;
    test.nested = nested;
    return test;
  }

  @Get("/ok")
  async getOK(): Promise<TestNestedEnum2> {
    const test = new TestNestedEnum2();
    const nested = new NestedEnum2();
    nested.value = EnumValue.One;
    test.nested = nested;
    return test;
  }
```

**Comment by ljonathanl** [comment]
Thx for the help but I have the same error. 

@Romakita I'm connected on slack if you need more test

**Comment by Romakita** [comment]
Works as expected. Checkout this example: https://github.com/Romakita/tsed-enum-issue-1534

See you
Romain

**Comment by ljonathanl** [comment]
I have found where the error come from.
I have used tsed-cli to generate the package.json with babel option.

I have the error for build and start, if I use babel :

```
build: npm run tsc && babel src --out-dir dist --extensions ".ts,.tsx" --source-maps inline
start: "babel-watch --extensions .ts src/index.ts"
```

But I have no error when I use the default option:

```
"build": "npm run tsc",
"start": "tsnd --inspect --ignore-watch node_modules --respawn --transpile-only -r tsconfig-paths/register src/index.ts",
```

Do you recommand to not use babel ?

**Comment by Romakita** [comment]
Haaaaaa. So can you send me the reproducible repository example. I’ll try to fix the issue ;)

**Comment by Romakita** [comment]
Babel transpile differently the code and decorators. But this is a bug that must be fixed by us ^^

**Comment by ljonathanl** [comment]
You can find the repository here : https://github.com/ljonathanl/tsed-enum-issue-1534

I have change package.json to use babel and add .babelrc
