### ISSUE TITLE
[BUG] Surprise stop of static serving

### ISSUE THREAD

**Issue by eddow** [TypedProject/ts-express-decorators#1600]
## Information

- **Version:** 6.73.9
- Packages: comon+express

As I was developing and all was going well, some `npm i` - I think, it might be something else I did - made my SPA stop serving the static content

## Example

I isolated the code, removing all the API, DB, &c. to be sure it was from there, I reached this (only typescript file from the server)

```
import { join } from "path";
import { $log, Configuration, Inject, PlatformApplication, Res } from "@tsed/common";
import { PlatformExpress } from "@tsed/platform-express";
import config from '@config';

const rootDir = __dirname;
const clientDir = join(rootDir, '../client');
console.log('clientDir: ' + clientDir);

@Configuration({
	rootDir,
	port: config.http.port,
	statics: {"/": [{root: clientDir}]}
})
export class Server {}

async function bootstrap() {
	try {
		$log.debug("Start server...");
		const platform = await PlatformExpress.bootstrap(Server, {});
		await platform.listen();
		$log.debug("Server initialized");
	} catch (er) {
		$log.error(er);
	}
}

bootstrap();
```

## Acceptance criteria

- For the files from `clientDir` [ie. `dist/client`] to be served statically, instead of a 404.

I provided a [repository](https://github.com/eddow/eddow-bug-expo/tree/tsed-statics)

Further details:

(hint: it seems the statics are not taken in consideration in the routes)

Debug log
```
clientDir: C:\dev\github\eddow-bug-expo\dist\client
[2021-10-25T02:54:49.961] [DEBUG] [TSED] - Start server...
[2021-10-25T02:54:50.051] [INFO ] [TSED] - Call hook $beforeInit
[.....]
[2021-10-25T02:39:50.500] [INFO ] [TSED] - Call hook $afterRoutesInit
[2021-10-25T02:39:50.501] [INFO ] [TSED] - Routes mounted :
[2021-10-25T02:39:50.502] [INFO ] [TSED] - 
┌────────┬──────────┬──────────────┐
```

Error when loading `http://localhost:4004/index.html`
```
  error: {
    name: 'NOT_FOUND',
    message: 'Resource "/index.html" not found',
    status: 404,
    errors: [],
    stack: 'NOT_FOUND: Resource "/index.html" not found\n' +
      '    at PlatformExceptions.resourceNotFound (C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\platform-exceptions\\lib\\index.js:233:23)\n' +
      '    at C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\platform-express\\lib\\components\\PlatformExpress.js:39:128\n' +
      '    at Layer.handle [as handle_request] (C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
      '    at trim_prefix (C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\index.js:317:13)\n' +
      '    at C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\index.js:284:7\n' +
      '    at Function.process_params (C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\index.js:335:12)\n' +
      '    at next (C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\index.js:275:10)\n' +
      '    at PlatformExpressHandler.next (C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\common\\lib\\index.js:1077:47)\n' +
      '    at PlatformExpressHandler.onSuccess (C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\common\\lib\\index.js:1017:17)\n' +
      '    at C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\common\\lib\\index.js:947:29\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  stack: 'NOT_FOUND: Resource "/index.html" not found\n' +
    '    at PlatformExceptions.resourceNotFound (C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\platform-exceptions\\lib\\index.js:233:23)\n' +
    '    at C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\platform-express\\lib\\components\\PlatformExpress.js:39:128\n' +
    '    at Layer.handle [as handle_request] (C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at trim_prefix (C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\index.js:317:13)\n' +
    '    at C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\index.js:284:7\n' +
    '    at Function.process_params (C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\index.js:335:12)\n' +
    '    at next (C:\\dev\\github\\eddow-bug-expo\\node_modules\\express\\lib\\router\\index.js:275:10)\n' +
    '    at PlatformExpressHandler.next (C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\common\\lib\\index.js:1077:47)\n' +
    '    at PlatformExpressHandler.onSuccess (C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\common\\lib\\index.js:1017:17)\n' +
    '    at C:\\dev\\github\\eddow-bug-expo\\node_modules\\@tsed\\common\\lib\\index.js:947:29\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
```

**Comment by eddow** [comment]
Perfect, good job guys! I now wonder why it worked before :p

**Comment by Romakita** [comment]
I added new options to allow mounting statics before routes. Unfortunatly I haven’t seen the side effect on the actual behavior. Sorry ;)
