### ISSUE TITLE
Cannot read property 'addRoute' of undefined

### ISSUE THREAD

**Issue by jpc-dnr** [TypedProject/ts-express-decorators#1621]
## Information

- **Version:** >= 6.75.2

Since version 6.75.2, there is an error at startup :

```
2021-11-02T11:44:03.130] [INFO ] [TSED] - Call hook $beforeInit
[2021-11-02T11:44:03.200] [FATAL] [default] - Application error TypeError: Cannot read property 'addRoute' of undefined
    at /path/to/folder/node_modules/@tsed/common/lib/index.js:1527:14
    at Map.forEach (<anonymous>)
    at PlatformControllerBuilder.buildEndpoint (/path/to/folder/node_modules/@tsed/common/lib/index.js:1522:59)
    at /path/to/folder/node_modules/@tsed/common/lib/index.js:1491:12
    at Array.forEach (<anonymous>)
    at PlatformControllerBuilder.buildEndpoints (/path/to/folder/node_modules/@tsed/common/lib/index.js:1490:15)
    at PlatformControllerBuilder.build (/path/to/folder/node_modules/@tsed/common/lib/index.js:1453:6)
    at /path/to/folder/node_modules/@tsed/common/lib/index.js:2420:56
    at Array.map (<anonymous>)
    at Platform.buildControllers (/path/to/folder/node_modules/@tsed/common/lib/index.js:2418:55)
    at Platform.$onInit (/path/to/folder/node_modules/@tsed/common/lib/index.js:2344:10)
    at Map.emit (/path/to/folder/node_modules/@tsed/di/lib/index.js:345:13)
    at Map.load (/path/to/folder/node_modules/@tsed/di/lib/index.js:1774:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PlatformExpress.loadInjector (/path/to/folder/node_modules/@tsed/common/lib/index.js:2900:5)
    at async PlatformExpress.runLifecycle (/path/to/folder/node_modules/@tsed/common/lib/index.js:2886:5)
```

It works fine with version 6.75.1

I tried with all versions 6.75.2 to 6.75.10, the issue is present

**Comment by Romakita** [comment]
Have you the same version between all tsed packages ? Because, It works for me!

**Comment by jpc-dnr** [comment]
Thanks for your answer!

I have these dependencies in my project:

```json
"@tsed/ajv": "6.75.2",
"@tsed/common": "6.75.2",
"@tsed/core": "6.75.2",
"@tsed/di": "6.75.2",
"@tsed/openspec": "6.75.2",
"@tsed/platform-express": "6.75.2",
"@tsed/schema": "6.75.2",
"@tsed/swagger": "6.75.2",
```

Do you see something wrong?

I am doing the following in the `$beforeInit` hook:

```typescript
export class APIServer {
  @Configuration() private settings: Configuration;

  ...

  public async $beforeInit(): Promise<any> {
    this.settings.resolvers = [
      {
        get(token: any): any {
          return ...;
        }
      }
    ];
  }

  ...
}
```

Is there something wrong with that?

**Comment by Romakita** [comment]
Can you give me a reproducible example please ?

**Comment by jpc-dnr** [comment]
Sure, I managed to make a small reproducible project, I just gave you the access.

It is somehow related to the injection of `SwaggerService`in the `APIServer`class.

Thanks!

**Comment by Romakita** [comment]
ok I see the problem. Unfortunately, I can't rollback the actual code, because it solve issue with the DI/Controllers and AsyncFactory. The problem is, the class ApiServer is the only provider that not follow the DI graph resolution :( (it's a legacy from v5). It try to find a way to fix that. 

I also pushed some change on you repository example. You'll see in  the code, I use a custom module to load the SwaggerService and implement stuff. I think, it's a better approach, instead of loading SwaggerService in the Server class ;)

I'll come back to you if I found a solution,
See you
Romain

**Comment by jpc-dnr** [comment]
Thank your for your answer.

I understand that my code is legacy and using the custom module works for me so you don't need to find a solution to handle legacy way of doing things.

However, now I have an unwanted log that may come from Ts.ED :

```
...
[2021-11-03T10:29:45.679] [INFO ] [TSED] - Call hook $onReady
=== <ref *2> SwaggerService {
  injectorService: <ref *1> InjectorService(71) [Map] {
  ...
  }
}
```

Maybe this is not related, but do you have any idea where it can come from?

**Comment by Romakita** [comment]
If you update to the latest release, the log should be removed

**Comment by jpc-dnr** [comment]
It is indeed fixed, thank you
