### ISSUE TITLE
[BUG] Resolver/Services(Injectible) package is missing.

### ISSUE THREAD

**Issue by navalta3030** [TypedProject/ts-express-decorators#1673]
## Information

- **Version:** 6.93.0
- Packages: tsed ImportPackage

Working on GraphQL, added new service(Injectible) and suddenly all packages being scanned by component are missing.

## Server.ts

```
@Configuration({
  componentsScan: [
    `${rootDir}/gql/**/*.ts` // add this pattern to scan resolvers or datasources
  ],
  typegraphql: {
    default: {
      path: "/graphql"
    }
  },
  rootDir,
  acceptMimes: ["application/json"],
  httpPort: process.env.PORT || 8083,
  httpsPort: false,
  typeorm: typeormConfig,
  exclude: ["**/*.spec.ts"]
})
```

## Service added 
```
import { Injectable } from "@tsed/common";
import { Unauthorized } from "@tsed/exceptions";

import { Logger } from "../utils/logger";
import { User } from "../gql/schema/objects";
import { JWT_ACCESS_TOKEN_SECRET, TEMP_REDIS_DATABASE, TOKEN_DURATION } from "../utils/constants";
import jwt from "jsonwebtoken";

@Injectable()
export class AuthService {
  async refreshToken(token: string): Promise<string> {
    if (!token) {
      throw new Unauthorized("Token is invalid or has expired");
    }

    // temp logic since constants
    // should get userId via stored userId in redis
    const authToken = await this.decodeToken(token);

    if (TEMP_REDIS_DATABASE[token]) {
      return this.generateUserToken(authToken);
    }

    throw new Error(`Token: ${token} does not exists in our system`);
  }

  async decodeToken(token: string): Promise<User> {
    try {
      return jwt.verify(token as string, JWT_ACCESS_TOKEN_SECRET) as User;
    } catch (err) {
      Logger.error(err);
      throw new Unauthorized("Token is invalid or has expired");
    }
  }

  generateUserToken(user: User): string {
    return jwt.sign(user, JWT_ACCESS_TOKEN_SECRET, { expiresIn: TOKEN_DURATION });
  }
}
```

## Errors getting
```
Error: The "/Users/mark/Desktop/resolvex/dashboard/packages/account-service/src/gql/resolvers/clientsResolver.ts" package is missing.
    at importPackage (/Users/mark/Desktop/resolvex/dashboard/packages/account-service/node_modules/@tsed/core/src/utils/imports/importPackage.ts:6:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Acceptance criteria

- [x] be able to start (npm/yarn start).

**Comment by Romakita** [comment]
The problem is resolved?

**Comment by navalta3030** [comment]
Yes. Just had a typo on another file.
