### ISSUE TITLE
[BUG] CLI doesn't work with test 🐛

### ISSUE THREAD

**Issue by rustygreen** [TypedProject/ts-express-decorators#1687]
## Information

Creating a new project with the CLI using the following options:
```bash
tsed init .
```

### CLI Options
* Target: Express.js
* Architecture: Ts.ED
* Convention: Angular
* Features:
  * Socket.io
  * Swagger
  * Testing
  * Linter
* Linter: EsLint
* Extra linter tools: Prettier
* Package Manager: npm

### Dev Environment
**OS:** Windows 10
**Node Version:** 14.x

## Error
After the CLI completes the scaffolding and package installs, the app will fail to start when running `npm run start` (without any modifications):

### Error

```
[INFO] 19:16:50 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.4)
Debugger listening on ws://127.0.0.1:9229/557d0976-a10d-42b6-81c4-b7c24c560902
For help, see: https://nodejs.org/en/docs/inspector
[2021-12-15T19:16:54.487] [DEBUG] [TSED] - Start server...
[2021-12-15T19:16:54.505] [INFO ] [TSED] - Injector created... +14ms
ReferenceError: describe is not defined
    at Object.<anonymous> (C:\Workspace\xyz\hello-world.controller.integration.spec.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module._compile (C:\Workspace\xyz\node_modules\source-map-support\source-map-support.js:568:25)
    at Module.m._compile (C:\Users\RUSTYG~1\AppData\Local\Temp\ts-node-dev-hook-038365524880193735.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at require.extensions.<computed> (C:\Users\xyz~1\AppData\Local\Temp\ts-node-dev-hook-038365524880193735.js:71:20)
    at Object.nodeDevHook [as .ts] (C:\xyz\node_modules\ts-node-dev\lib\hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
```

**Comment by Romakita** [comment]
@rustygreen Hum maybe your issue is specific to windows os. I haven’t issue on lunix mac. Try to change the exclude option ^^ and tell me if it works
