### ISSUE TITLE
[BUG] Error while tsed init with GraphQL

### ISSUE THREAD

**Issue by p32929** [TypedProject/ts-express-decorators#1745]
## Information

- **Version:** 3.17.0 ( When I do `tsed --version`, I get this value )
- Packages: 
```
"dependencies": {
    "apollo-server-express": "2.25.2"
  },
  "devDependencies": {
    "@tsed/cli-plugin-mongoose": "3.17.0",
    "@tsed/cli-plugin-passport": "3.17.0"
  },
  "tsed": {
    "packageManager": "yarn",
    "convention": "default",
    "architecture": "default"
  }
```

I tried to `tsed init gtest` and this happened:

```
? What is your project name gtest
? Choose the target platform: Express.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project GraphQL, Database, Passport.js, Swagger, Bundler
? Choose a ORM manager Mongoose
? Choose your bundler Webpack
? Choose the package manager: Yarn
↓ Write RC files [SKIPPED]
> Install plugins
  √ Write package.json
  √ Installing dependencies using Yarn
  × Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper ajv cross-e…
  ■ Add devDependencies using Yarn
  ■ Clean
■ Load plugins
■ Install plugins dependencies
Error: Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper ajv cross-env dotenv @tsed/graphql apollo-datasource apollo-datasource-rest type-graphql graphql @tsed/swagger @tsed/platform-express body-parser cors compression cookie-parser express method-override
warning package.json: No license field
warning gtest@1.0.0: No license field
warning Pattern ["body-parser@^1.19.1"] is trying to unpack in the same destination "C:\\Users\\MegaMind\\AppData\\Local\\Yarn\\Cache\\v6\\npm-body-parser-1.19.1-1499abbaa9274af3ecc9f6f10396c995943e31d4-integrity\\node_modules\\body-parser" as pattern ["body-parser@^1.18.3","body-parser@1.19.1","body-parser@1.19.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["express@^4.17.2"] is trying to unpack in the same destination "C:\\Users\\MegaMind\\AppData\\Local\\Yarn\\Cache\\v6\\npm-express-4.17.2-c18369f265297319beed4e5558753cc8c1364cb3-integrity\\node_modules\\express" as pattern ["express@^4.17.1","express@^4.17.1"]. This could result in non-deterministic behavior, skipping.
error An unexpected error occurred: "https://registry.yarnpkg.com/@tsed/typegraphql/-/typegraphql-6.98.5.tgz: Request failed \"404 Not Found\"".
yarn add v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "E:\\SourceCodes\\NodeJS\\Tests\\gtest\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at makeError (C:\Users\MegaMind\AppData\Roaming\npm\node_modules\@tsed\cli\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\MegaMind\AppData\Roaming\npm\node_modules\@tsed\cli\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  name: 'CLI_ERROR',
  cli: CliCore {},
  origin: Error: Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper ajv cross-env dotenv @tsed/graphql apollo-datasource apollo-datasource-rest type-graphql graphql @tsed/swagger @tsed/platform-express body-parser cors compression cookie-parser express method-override
  warning package.json: No license field
  warning gtest@1.0.0: No license field
  warning Pattern ["body-parser@^1.19.1"] is trying to unpack in the same destination "C:\\Users\\MegaMind\\AppData\\Local\\Yarn\\Cache\\v6\\npm-body-parser-1.19.1-1499abbaa9274af3ecc9f6f10396c995943e31d4-integrity\\node_modules\\body-parser" as pattern ["body-parser@^1.18.3","body-parser@1.19.1","body-parser@1.19.1"]. This could result in non-deterministic behavior, skipping.
  warning Pattern ["express@^4.17.2"] is trying to unpack in the same destination "C:\\Users\\MegaMind\\AppData\\Local\\Yarn\\Cache\\v6\\npm-express-4.17.2-c18369f265297319beed4e5558753cc8c1364cb3-integrity\\node_modules\\express" as pattern ["express@^4.17.1","express@^4.17.1"]. This could result in non-deterministic behavior, skipping.
  error An unexpected error occurred: "https://registry.yarnpkg.com/@tsed/typegraphql/-/typegraphql-6.98.5.tgz: Request failed \"404 Not Found\"".
  yarn add v1.22.17
  [1/4] Resolving packages...
  [2/4] Fetching packages...
  info If you think this is a bug, please open a bug report with the information provided in "E:\\SourceCodes\\NodeJS\\Tests\\gtest\\yarn-error.log".
  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
      at makeError (C:\Users\MegaMind\AppData\Roaming\npm\node_modules\@tsed\cli\node_modules\execa\lib\error.js:59:11)
      at handlePromise (C:\Users\MegaMind\AppData\Roaming\npm\node_modules\@tsed\cli\node_modules\execa\index.js:114:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    shortMessage: 'Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper ajv cross-env dotenv @tsed/graphql apollo-datasource apollo-datasource-rest type-graphql graphql @tsed/swagger @tsed/platform-express body-parser cors compression cookie-parser express method-override',
    command: 'yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper ajv cross-env dotenv @tsed/graphql apollo-datasource apollo-datasource-rest type-graphql graphql @tsed/swagger @tsed/platform-express body-parser cors compression cookie-parser express method-override',
    exitCode: 1,
    signal: undefined,
    signalDescription: undefined,
    stdout: 'yarn add v1.22.17\n' +
      '[1/4] Resolving packages...\n' +
      '[2/4] Fetching packages...\n' +
      'info If you think this is a bug, please open a bug report with the information provided in "E:\\\\SourceCodes\\\\NodeJS\\\\Tests\\\\gtest\\\\yarn-error.log".\n' +
      'info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.',
    stderr: 'warning package.json: No license field\n' +
      'warning gtest@1.0.0: No license field\n' +
      'warning Pattern ["body-parser@^1.19.1"] is trying to unpack in the same destination "C:\\\\Users\\\\MegaMind\\\\AppData\\\\Local\\\\Yarn\\\\Cache\\\\v6\\\\npm-body-parser-1.19.1-1499abbaa9274af3ecc9f6f10396c995943e31d4-integrity\\\\node_modules\\\\body-parser" as pattern ["body-parser@^1.18.3","body-parser@1.19.1","body-parser@1.19.1"]. This could result in non-deterministic behavior, skipping.\n' +
      'warning Pattern ["express@^4.17.2"] is trying to unpack in the same destination "C:\\\\Users\\\\MegaMind\\\\AppData\\\\Local\\\\Yarn\\\\Cache\\\\v6\\\\npm-express-4.17.2-c18369f265297319beed4e5558753cc8c1364cb3-integrity\\\\node_modules\\\\express" as pattern ["express@^4.17.1","express@^4.17.1"]. This could result in non-deterministic behavior, skipping.\n' +
      'error An unexpected error occurred: "https://registry.yarnpkg.com/@tsed/typegraphql/-/typegraphql-6.98.5.tgz: Request failed \\"404 Not Found\\"".',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper ajv cross-env dotenv @tsed/graphql apollo-datasource apollo-datasource-rest type-graphql graphql @tsed/swagger @tsed/platform-express body-parser cors compression cookie-parser express method-override
warning package.json: No license field
warning gtest@1.0.0: No license field
warning Pattern ["body-parser@^1.19.1"] is trying to unpack in the same destination "C:\\Users\\MegaMind\\AppData\\Local\\Yarn\\Cache\\v6\\npm-body-parser-1.19.1-1499abbaa9274af3ecc9f6f10396c995943e31d4-integrity\\node_modules\\body-parser" as pattern ["body-parser@^1.18.3","body-parser@1.19.1","body-parser@1.19.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["express@^4.17.2"] is trying to unpack in the same destination "C:\\Users\\MegaMind\\AppData\\Local\\Yarn\\Cache\\v6\\npm-express-4.17.2-c18369f265297319beed4e5558753cc8c1364cb3-integrity\\node_modules\\express" as pattern ["express@^4.17.1","express@^4.17.1"]. This could result in non-deterministic behavior, skipping.
error An unexpected error occurred: "https://registry.yarnpkg.com/@tsed/typegraphql/-/typegraphql-6.98.5.tgz: Request failed \"404 Not Found\"".
yarn add v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "E:\\SourceCodes\\NodeJS\\Tests\\gtest\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at makeError (C:\Users\MegaMind\AppData\Roaming\npm\node_modules\@tsed\cli\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\MegaMind\AppData\Roaming\npm\node_modules\@tsed\cli\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper ajv cross-env dotenv @tsed/graphql apollo-datasource apollo-datasource-rest type-graphql graphql @tsed/swagger @tsed/platform-express body-parser cors compression cookie-parser express method-override',
  command: 'yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper ajv cross-env dotenv @tsed/graphql apollo-datasource apollo-datasource-rest type-graphql graphql @tsed/swagger @tsed/platform-express body-parser cors compression cookie-parser express method-override',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn add v1.22.17\n' +
    '[1/4] Resolving packages...\n' +
    '[2/4] Fetching packages...\n' +
    'info If you think this is a bug, please open a bug report with the information provided in "E:\\\\SourceCodes\\\\NodeJS\\\\Tests\\\\gtest\\\\yarn-error.log".\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.',
  stderr: 'warning package.json: No license field\n' +
    'warning gtest@1.0.0: No license field\n' +
    'warning Pattern ["body-parser@^1.19.1"] is trying to unpack in the same destination "C:\\\\Users\\\\MegaMind\\\\AppData\\\\Local\\\\Yarn\\\\Cache\\\\v6\\\\npm-body-parser-1.19.1-1499abbaa9274af3ecc9f6f10396c995943e31d4-integrity\\\\node_modules\\\\body-parser" as pattern ["body-parser@^1.18.3","body-parser@1.19.1","body-parser@1.19.1"]. This could result in non-deterministic behavior, skipping.\n' +
    'warning Pattern ["express@^4.17.2"] is trying to unpack in the same destination "C:\\\\Users\\\\MegaMind\\\\AppData\\\\Local\\\\Yarn\\\\Cache\\\\v6\\\\npm-express-4.17.2-c18369f265297319beed4e5558753cc8c1364cb3-integrity\\\\node_modules\\\\express" as pattern ["express@^4.17.1","express@^4.17.1"]. This could result in non-deterministic behavior, skipping.\n' +
    'error An unexpected error occurred: "https://registry.yarnpkg.com/@tsed/typegraphql/-/typegraphql-6.98.5.tgz: Request failed \\"404 Not Found\\"".',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

## Acceptance criteria

- [ ] Being able to init tsed that includes GraphQL

**Comment by Romakita** [comment]
For me all works fine :)

Maybe a network error ?

**Comment by p32929** [comment]
Surprisingly, its working now :/ Not sure what happened :/

**Comment by Romakita** [comment]
In your log, it appears is a network issue

error An unexpected error occurred: "https://registry.yarnpkg.com/@tsed/typegraphql/-/typegraphql-6.98.5.tgz: Request failed \"404 Not Found\"".

Maybe you have ran the cli during a package publication ^^ or maybe yarn registry wasn’t up to date. 

See you
