### ISSUE TITLE
[BUG] POST params and files not receive body param empty

### ISSUE THREAD

**Issue by Paul75** [TypedProject/ts-express-decorators#1776]
## Information

- **Version:** 6.102.8
- Packages:

Add params and files in controller not receive body (empty)

## Example

```ts
@Post('/')
  @Status(201)
  @Returns(201, Product).ContentType('application/json')
  @Returns(401, Unauthorized).Description('Unauthorized')
  @Returns(403, Forbidden).Description('Forbidden')
  async addProduct(
    @Description('Produit à ajouter')
    @Required()
    @BodyParams('product', Product)
    product: Product,
    @Description('Images du produit')
    @MultipartFile('images', 5)
    images: PlatformMulterFile[]
  ): Promise<Product[]> {
    **console.log(product);** <== empty product
    // console.log(images);
    let imagesProducts: ImagesProduct[] = [];

    for (const key in images) {
      if (Object.prototype.hasOwnProperty.call(images, key)) {
        const image = images[key];
        const urlImage = path.basename(image.path);
        // console.log(urlImage);

        const mimetype: MimesTypes|undefined = await this.mimesTypesService.findOne({
          where: {
            typeMIME: image.mimetype,
          },
        });

        if (mimetype) {
          imagesProducts.push({
            data: urlImage,
            mimeType: mimetype,
          });
        }
      }
    }

    // console.log(imagesProducts);
    product.images = imagesProducts;

    console.log(product instanceof Product);
    console.log(product);

    return this.productService.save([product]);
  }
```

log receive param : 

```
Product {
  id: undefined,
  images: undefined,
  title: undefined,
  description: undefined,
  category: undefined,
  brand: undefined,
  size: undefined,
  price: undefined,
  weight: undefined,
  user: undefined
}
```

Error :

```
{
  "name": "QueryFailedError",
  "message": "ER_NO_DEFAULT_FOR_FIELD: Field 'title' doesn't have a default value",
  "status": 500,
  "errors": [],
  "stack": "QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'title' doesn't have a default value\n    at QueryFailedError.TypeORMError [as constructor] (/home/pkbp512/www/VEEP/back_end/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/home/pkbp512/www/VEEP/back_end/src/error/QueryFailedError.ts:9:9)\n    at Query.<anonymous> (/home/pkbp512/www/VEEP/back_end/src/driver/mysql/MysqlQueryRunner.ts:183:37)\n    at Query.<anonymous> (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/Connection.js:526:10)\n    at Query._callback (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/Connection.js:488:16)\n    at Query.Sequence.end (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)\n    at Query.ErrorPacket (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)\n    at Protocol._parsePacket (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/protocol/Protocol.js:291:23)\n    at Parser._parsePacket (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/protocol/Parser.js:433:10)\n    at Parser.write (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/protocol/Parser.js:43:10)\n    at Protocol.write (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/Connection.js:88:28)\n    at Socket.<anonymous> (/home/pkbp512/www/VEEP/back_end/node_modules/mysql/lib/Connection.js:526:10)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)"
}
```

Thanks

**Comment by Romakita** [comment]
Hello @Paul75 

Can you try this example please:
```typescript
  async addProduct(
    @Description('Produit à ajouter')
    @Required()
    @BodyParams('product', Product)
    product: Product,
    @Description('Images du produit')
    @MultipartFile('images', 5)
    images: PlatformMulterFile[],
    
    @Req() req: any
  ): Promise<Product[]> {
     console.log(req.body);  // tell if you have something
  }
```  
> req.body is the body payload from Express.js without transformation. It should be filled if it's a Ts.ED bug.

See you
Romain

**Comment by Paul75** [comment]
Hello,

In console have : 

```
[Object: null prototype] {
  product: '{\r\n' +
    '  "title": "ADD 1",\r\n' +
    '  "description": "Ajout test 1",\r\n' +
    '  "brand": {\r\n' +
    '    "id": 1,\r\n' +
    '    "title": "okeedoc",\r\n' +
    '    "numeroMarque": "4611021"\r\n' +
    '  },\r\n' +
    '  "category": [{\r\n' +
    '    "id": "12",\r\n' +
    '    "title": "Bottes",\r\n' +
    '    "description": "Bottes",\r\n' +
    '    "last": true,\r\n' +
    '    "isActive": true\r\n' +
    '  }],\r\n' +
    '  "size": "string",\r\n' +
    '  "price": 0,\r\n' +
    '  "weight": 0,\r\n' +
    '  "user": {\r\n' +
    '    "id": 1,\r\n' +
    '    "pseudo": "Paul",\r\n' +
    '    "civility": "Monsieur",\r\n' +
    '    "lastname": "BOREL",\r\n' +
    '    "firstname": "Paul",\r\n' +
    '    "verified": false\r\n' +
    '  }\r\n' +
    '}'
}
```

Thanks

**Comment by Romakita** [comment]
ok the content is a string. It's not parsed

**Comment by Paul75** [comment]
That means I do wrong ???

**Comment by Romakita** [comment]
Your front-end send the body as JSON stringified in the product field. So it's normal to not works. The framework cannot cover all usecases if you make something special ^^. I'm not sure if it's the framework responsability to cover that...

**Comment by Paul75** [comment]
I do the query from swagger ....

![screenshot-127 0 0 1_3000-2022 02 22-15_06_04](https://user-images.githubusercontent.com/457062/155148504-f9d03ab6-401c-423d-9f33-a92f9c2ef56c.png)

**Comment by Romakita** [comment]
Yes I understand the point, but, it's because swagger serialize the payload on the field, dut to the content-type is a `multipart/form-data`. It's not an `application/json`.

**Comment by Paul75** [comment]
Hello, If i understant I must not pass BodyParams but Req ?

**Comment by Romakita** [comment]
The solution right now, is to implement a custom pipe: https://tsed.io/docs/pipes.html And parse the json payload before consume it with BodyParams.

**Comment by Paul75** [comment]
Because if i remove : @MultipartFile('images', 5)
    images: PlatformMulterFile[]

the body work ....

**Comment by Romakita** [comment]
>Hello, If i understant I must not pass BodyParams but Req ?
Not exactly. In normal way, the payload is parse by the bodyParser.json() when the content-type is `application/json`.

Using the `multipart/form-data`, the bodyParser.json() won't have any effect and the req.body won't be parsed. This is why you have as string in req.body.product.

When you use MultipartFile decorator, Ts.ED will use the [multer](https://www.npmjs.com/package/multer). His behavior is different from bodyParser.json().

>Because if i remove : @MultipartFile('images', 5)
images: PlatformMulterFile[]
the body work ....

Probably because, the multer middleware isn't used ^^

**Comment by Romakita** [comment]
If you have a time, can you create a small project on github to reproduce the issue please?

**Comment by Paul75** [comment]
Okay I do Pipe but same problem When I do  : 

```
async addProduct(
    @Description('Produit à ajouter')
    @Required()
    @UsePipe(ParseBodyJsonPipe)
    @BodyParams('product', Product)
    product: Product,
    @Description('Images du produit')
    @MultipartFile('images', 5)
    images: PlatformMulterFile[]
  ) {
    console.log(product);
  }
```

And Pipe : 

```
@Injectable()
export class ParseBodyJsonPipe implements PipeMethods<string> {
  transform(value: string, metadata: JsonParameterStore): string {
      console.log('ParseBodyJsonPipe', value);
      
    const val = JSON.parse(value);

    return val;
  }
}
```

Receive in console : 
```
ParseBodyJsonPipe Product {
  id: undefined,
  images: undefined,
  title: undefined,
  description: undefined,
  category: undefined,
  brand: undefined,
  size: undefined,
  price: undefined,
  weight: undefined,
  user: undefined
}
```
Sorry ...

**Comment by Romakita** [comment]
Why are you sorry ?

**Comment by Paul75** [comment]
because I'm stupid or not understand because the value is the same that means not receive the Product data with datas ...

**Comment by Romakita** [comment]
Can you try this:
```typescript
@Injectable({
   priority: -1
})
export class ParseBodyJsonPipe implements PipeMethods<string> {
  transform(value: string, metadata: JsonParameterStore): string {
      console.log('ParseBodyJsonPipe', typeof value, value);
      
    const val = JSON.parse(value);
   
    console.log(val)
    return val;
  }
}
```

**Comment by Paul75** [comment]
okay thanks now it have data on the body .....

**Comment by Romakita** [comment]
Ok, it's related to the `priority: -1`. DeserializePipe have a normal priority, but the custom pipe are appended with the DeserializePipe (normal). Adding priority change the Pipe order and run your custom pipe in first ^^.

**Comment by Romakita** [comment]
So it's ok for you ?

**Comment by Paul75** [comment]
Yes that works now. Thanks for rapidly to help me

**Comment by Romakita** [comment]
I think the problem is about the missing documentation on this usecase. I'll add your ticket on the todo on the board to improve the documentation ^^

Have a nice day and thanks for the issue ;)
Romain
