### ISSUE TITLE
[BUG] UseAfter decorator does not work for error middleware

### ISSUE THREAD

**Issue by zenkdev** [TypedProject/ts-express-decorators#1793]
## Information

- **Version:** 6.103.2
- Packages:

I have error middleware that should be applied for certain controllers/endpoints.
It worked in version 6.23.1 but now every method with this middleware returns the error:
```bash
LOG 4 Mar 16:45:35 [ERROR] [TSED] - {
  method: 'GET',
  url: '/apps/api/users/current/applications',
  headers: {
    host: 'localhost:3000',
    connection: 'keep-alive',
    pragma: 'no-cache',
    'cache-control': 'no-cache',
    'content-type': 'application/json; charset=utf-8',
    accept: 'application/json',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36',
    referer: 'http://localhost:3000/apps/editor/621210/KPI',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en,ru;q=0.9,en-US;q=0.8',
  },
  body: {},
  query: {},
  params: {},
  reqId: '27d22fb22d864fdaa4f7be15bbb962dd',
  time: 2022-03-04T13:45:35.280Z,
  duration: 233,
  error: {
    name: 'NOT_FOUND',
    message: 'Resource "/apps/api/users/current/applications" not found',
    status: 404,
    errors: [],
    stack: 'NOT_FOUND: Resource "/apps/api/users/current/applications" not found\n' +
      '    at PlatformExceptions.resourceNotFound (C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\platform-exceptions\\src\\services\\PlatformExceptions.ts:51:23)\n' +
      '    at C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\platform-express\\src\\components\\PlatformExpress.ts:98:81\n' +
      '    at Layer.handle [as handle_request] (C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
      '    at trim_prefix (C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\index.js:323:13)\n' +
      '    at C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\index.js:284:7\n' +
      '    at Function.process_params (C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\index.js:341:12)\n' +
      '    at next (C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\index.js:275:10)\n' +
      '    at PlatformExpressHandler.next (C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\common\\src\\services\\PlatformHandler.ts:261:47)\n' +
      '    at PlatformExpressHandler.onSuccess (C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\common\\src\\services\\PlatformHandler.ts:216:17)\n' +
      '    at C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\common\\src\\services\\PlatformHandler.ts:156:29'
  },
  stack: 'NOT_FOUND: Resource "/apps/api/users/current/applications" not found\n' +
    '    at PlatformExceptions.resourceNotFound (C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\platform-exceptions\\src\\services\\PlatformExceptions.ts:51:23)\n' +
    '    at C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\platform-express\\src\\components\\PlatformExpress.ts:98:81\n' +
    '    at Layer.handle [as handle_request] (C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at trim_prefix (C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\index.js:323:13)\n' +
    '    at C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\index.js:284:7\n' +
    '    at Function.process_params (C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\index.js:341:12)\n' +
    '    at next (C:\\dev\\confirmit.appstudio.client\\node_modules\\express\\lib\\router\\index.js:275:10)\n' +
    '    at PlatformExpressHandler.next (C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\common\\src\\services\\PlatformHandler.ts:261:47)\n' +
    '    at PlatformExpressHandler.onSuccess (C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\common\\src\\services\\PlatformHandler.ts:216:17)\n' +
    '    at C:\\dev\\confirmit.appstudio.client\\node_modules\\@tsed\\common\\src\\services\\PlatformHandler.ts:156:29'
}
```

## Example

```ts
/* UsersController .ts */
import {Req, Res, UseAfter} from '@tsed/common';
import {Controller} from '@tsed/di';
import {PathParams} from '@tsed/platform-params';
import {Get, Returns} from '@tsed/schema';

import {ForbiddenNotFoundErrorMiddleware} from '../../middlewares/error-handling/ForbiddenNotFoundErrorMiddleware';
import {CmlStorageService, restClientProvider} from '../../studio-utils';

@Controller('/users')
@UseAfter(ForbiddenNotFoundErrorMiddleware)
export class UsersController {
  @Get('/current/applications')
  @(Returns(200, Object).ContentType('application/json'))
  async getApplications(@Req() req: Req, @Res() res: Res): Promise<any> {
    const restClient = await restClientProvider.getRestClient(req, res);
    const applicationsResponse = await restClient.get(req.apis.applications);
    const {items: applications} = applicationsResponse.json();
    return applications;
  }
}

/* ForbiddenNotFoundErrorMiddleware.ts */
import {FetchError, isRestClientFetchError} from '@confirmit/rest-client';
import {Err, Next, Res} from '@tsed/common';
import {Middleware, MiddlewareMethods} from '@tsed/platform-middlewares';

@Middleware()
export class ForbiddenNotFoundErrorMiddleware implements MiddlewareMethods {
  use(@Err() err: unknown, @Res() res: Res, @Next() next: Next) {
    if (isRestClientFetchError(err)) {
      const fetchError = err as FetchError;
      if ([403, 404].includes(fetchError.status)) {
        res.sendStatus(404).end();
        return;
      }
    }
    next(err);
  }
}
```

## Acceptance criteria

- [ ] It should be possible to attach error middleware to certain controllers/endpoints

**Comment by Romakita** [comment]
Are you on Koa ?

**Comment by Romakita** [comment]
But it would be preferable to use Interceptor instead of middleware.

```typescript
import {NotFound} from "@tsed/exceptions";

@Injectable()
export class ForbiddenNotFoundErrorInterceptor {
  async intercept(context: InterceptorContext<any>, next: InterceptorNext) {
    try {
      return await next();
    } catch (er) {
      if (isRestClientFetchError(err)) {
        const fetchError = err as FetchError;
        if ([403, 404].includes(fetchError.status)) {
          throw new NotFound();
        }
      }
    }
  }
}
```

**Comment by zenkdev** [comment]
> Are you on Koa ?

No, I'm using express.

**Comment by zenkdev** [comment]
> But it would be preferable to use Interceptor instead of middleware.

Probably, but I would have to add `Interceptor` to each controller method whereas  `UseBefore` can be applied to the entire controller.

BTW Interceptor works fine. 

Thank you.

**Comment by Romakita** [comment]
it's possible to have the same behavior:

```typescript
import {useMethodDecorators} from "@tsed/core";

export function UseInterceptor(interceptor) {
  return useMethodDecorators(Intercept(interceptor))
}
```

**Comment by zenkdev** [comment]
> it's possible to have the same behavior:

Unfortunately it doesn't work
```ts
@Controller('/users')
@UseInterceptor(ForbiddenNotFoundErrorInterceptor)
export class UsersController {
  @Get('/current/applications')
  @(Returns(200, Object).ContentType('application/json'))
  async getApplications(@Req() req: GatewayRequest, @Res() res: GatewayResponse): Promise<any> {
    throw new FetchError({status: 403});
  }
```

This works fine
```ts
@Controller('/users')
export class UsersController {
  @Get('/current/applications')
  @(Returns(200, Object).ContentType('application/json'))
  @Intercept(ForbiddenNotFoundErrorInterceptor)
  async getApplications(@Req() req: GatewayRequest, @Res() res: GatewayResponse): Promise<any> {
    throw new FetchError({status: 403});
  }
```

**Comment by Romakita** [comment]
It should works. useMethodDecorators add the interceptor for each methods.

**Comment by zenkdev** [comment]
> It should works. useMethodDecorators add the interceptor for each methods.

Sorry, but it does not. I checked twice.

**Comment by Romakita** [comment]
Ok. I'll try to repro. This is the only solution that I can propose you and I have not enought time to work on it right know.

The issue is added on the board.

**Comment by Romakita** [comment]
Another way is to use the exception filter: https://tsed.io/docs/exceptions.html#exception-filter
It work on all errors emitted by your controllers :)

**Comment by Romakita** [comment]
Ok sorry for the wrong example with the interceptor. Here is the right implementation to decorate all methods of a class:

```typescript
import {NotFound} from "@tsed/exceptions";
import {Injectable, Intercept, InterceptorContext, InterceptorNext} from "@tsed/di";
import {decorateMethodsOf} from "@tsed/core";


export function UseInterceptor(interceptor: any) {
  return (target) => decorateMethodsOf(target, Intercept(interceptor));
}

@Injectable()
export class ForbiddenNotFoundErrorInterceptor {
  async intercept(context: InterceptorContext<any>, next: InterceptorNext) {
    try {
      return await next();
    } catch (err) {
      const fetchError = err as any;
      if ([403, 404].includes(fetchError.status)) {
        throw new NotFound("Not found");
      }
    }
  }
}

@Controller("/hello-world")
@UseInterceptor(ForbiddenNotFoundErrorInterceptor)
export class HelloWorldController {
  @Get("/")
  get() {
    const error: any = new Error("test");
    error.status = 403;

    throw error;
  }
}

```

**Comment by Romakita** [comment]
Works as expected, the middleware is correctly called:

https://github.com/Romakita/tsed-1793

I close the issue, until you haven't a reproducible example ;)

See you
Romain

**Comment by zenkdev** [comment]
> ```ts
> export function UseInterceptor(interceptor: any) {
>   return (target) => decorateMethodsOf(target, Intercept(interceptor));
> }
> ```

Thanks for example. But I have an error in my project
```bash
LOG 5 Mar 14:57:05 [INFO] [TSED] - Providers loaded... +3419ms
LOG 5 Mar 14:57:05 [INFO] [TSED] - Build providers +1ms
ERROR 5 Mar 14:57:05 Failed to start server: TypeError: Cannot assign to read only property 'logger' of object '#<UsersController>'
{"EventTime":"2022-03-05T14:57:05.502+03:00","InitiatingService":"Confirmit.AppStudio.Gateway","Logger":"Studio.Gateway","Message":"Failed to start server: TypeError: Cannot assign to read only property 'logger' of object '#<UsersCo
ntroller>'","Service":"Confirmit.AppStudio.Gateway","ServiceVersion":"(default)","Severity":"ERROR"}
(node:15600) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'logger' of object '#<UsersController>'
    at Map.bindInterceptor (C:\dev\confirmit.appstudio.client\node_modules\@tsed\di\src\services\InjectorService.ts:485:26)
    at C:\dev\confirmit.appstudio.client\node_modules\@tsed\di\src\services\InjectorService.ts:377:16
    at Array.forEach (<anonymous>)
    at Map.bindInjectableProperties (C:\dev\confirmit.appstudio.client\node_modules\@tsed\di\src\services\InjectorService.ts:362:31)
    at Map.resolve (C:\dev\confirmit.appstudio.client\node_modules\@tsed\di\src\services\InjectorService.ts:646:12)
    at Map.invoke (C:\dev\confirmit.appstudio.client\node_modules\@tsed\di\src\services\InjectorService.ts:216:39)
    at Map.loadSync (C:\dev\confirmit.appstudio.client\node_modules\@tsed\di\src\services\InjectorService.ts:264:14)
    at Map.load (C:\dev\confirmit.appstudio.client\node_modules\@tsed\di\src\services\InjectorService.ts:308:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at PlatformBuilder.loadInjector (C:\dev\confirmit.appstudio.client\node_modules\@tsed\common\src\builder\PlatformBuilder.ts:205:5)
    at PlatformBuilder.runLifecycle (C:\dev\confirmit.appstudio.client\node_modules\@tsed\common\src\builder\PlatformBuilder.ts:183:5)
    at bootstrap (C:\dev\confirmit.appstudio.client\src\gateway\server.ts:26:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). T
o terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
/Alexander

**Comment by Romakita** [comment]
This error is strange... Have you the same package version for all tsed packages? Have you installed the latest logger version 6.1.0 ?
My example works, so you can checkout it. I haven't your project, so I'm not able to help you, If you are not able to reproduce the bug outside of your project. Please take a time to do this work (it's your responsibility ;)).

See you
Romain

**Comment by Romakita** [comment]
Also my repo example show a working example with the middleware added with UseAfter. So please take a time to read my example... otherwise I'll feel like I've wasted my time giving you a working example. And it's really sad

**Comment by zenkdev** [comment]
> Also my repo example show a working example with the middleware added with UseAfter. So please take a time to read my example... otherwise I'll feel like I've wasted my time giving you a working example. And it's really sad

Sorry, I didn't mean to be rude. I checked your example, but my project has a very complicated setup. This is probably my problem. I'll check everything again. Thanks for your help, I appreciate it.
/Alexander

**Comment by zenkdev** [comment]
Good evening Romain. I reproduced all bug described above. Please take a look https://github.com/Romakita/tsed-1793/pull/1
/Alexander

**Comment by Romakita** [comment]
Perfect @zenkdev, I'll take a time to review your PR ;) Good job

**Comment by Romakita** [comment]
@zenkdev I fixed the issue with the interceptor ;) thank for the repo
Also for Middleware error, the repo help me, because it's a very specific usecase. I haven't fixed this issue, but I see where is the problem thanks ;)

**Comment by joeynq** [comment]
> Another way is to use the exception filter: https://tsed.io/docs/exceptions.html#exception-filter It work on all errors emitted by your controllers :)

This is not working with me:

```ts
// ErrorFilter.ts
@Catch(Error)
export class ErrorFilter implements ExceptionFilterMethods {
  catch(exception: Exception, ctx: PlatformContext) {
    // BadRequest from Ajv validator didn't run through this function
  }
}

// Server.ts
import "./error-handler/ErrorFilter.ts"

@Configuration({
  // app config
})
export class Server {}
```
@Romakita

**Comment by Romakita** [comment]
Please fill another issue with a reproducible example. This issue is closed!

See you
Romain
