### ISSUE TITLE
[BUG] Migrate from v5 -  Cannot set property 'useClass' of undefined 

### ISSUE THREAD

**Issue by thanhchuongbmd** [TypedProject/ts-express-decorators#1833]
## Information

- **Version:** 6.x
- Packages:
    "@parse/node-apn": "3.1.0",
    "@tsed/common": "6.107.5",
    "@tsed/core": "6.107.5",
    "@tsed/exceptions": "6.107.5",
    "@tsed/platform-express": "^6.107.5",
    "@tsed/swagger": "6.107.5",
    "@tsed/typeorm": "6.107.5",
    "@tsed/json-mapper": "6.107.5",
    "@tsed/di": "6.107.5",

- When I run dev it throw err: 

`TypeError: Cannot set property 'useClass' of undefined
    at /migrate-tsed-v6/node_modules/@tsed/di/src/decorators/overrideProvider.ts:12:52
    at DecorateConstructor (/migrate-tsed-v6/node_modules/@tsed/core/node_modules/reflect-metadata/Reflect.js:541:33)
    at Object.decorate (/migrate-tsed-v6/node_modules/@tsed/core/node_modules/reflect-metadata/Reflect.js:130:24)
    at __decorate (/migrate-tsed-v6/src/middleware/response/CustomSendResponse.ts:4:92)
    at Object.<anonymous> (/migrate-tsed-v6/src/middleware/response/CustomSendResponse.ts:5:35)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module._compile (/migrate-tsed-v6/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/hv/2q6gs_ls6ybc45lrdyc9l_mm0000gn/T/ts-node-dev-hook-5312259257595304.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at require.extensions.<computed> (/private/var/folders/hv/2q6gs_ls6ybc45lrdyc9l_mm0000gn/T/ts-node-dev-hook-5312259257595304.js:71:20)
[ERROR] 15:54:42 TypeError: Cannot set property 'useClass' of undefined`

**Comment by Romakita** [comment]
It means you have an undefined class when you use OverrideProvider... please inspect your code.
Locate the file where you use the OverrideProvider decorator and give a reproducible example. The error isn't enough. Integration test work on my side since a long time.
See you
Romain

**Comment by thanhchuongbmd** [comment]
> OverrideProvider

Thank you, I see OverrideProvider in my code!
