### ISSUE TITLE
after upgrading to latest version server cannot get started throwing exception

### ISSUE THREAD

**Issue by shivanshtalwar0** [TypedProject/ts-express-decorators#1896]
## Information

- **Version:** 6.114.8
- Packages:
getting this error attaching stacktrace
```
[2022-05-12T04:06:16.578] [ERROR] [TSED] - TypeError: Cannot read properties of undefined (reading 'isStore')
    at Function.from (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/domain/JsonEntityStore.ts:215:17)
    at getJsonEntityStore (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/utils/getJsonEntityStore.ts:34:26)
    at JsonLazyRef.get schema [as schema] (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/domain/JsonLazyRef.ts:16:30)
    at lazyRefMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/components/lazyRefMapper.ts:18:22)
    at execMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
    at anyMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/components/anyMapper.ts:13:22)
    at execMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
    at itemMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/components/itemMapper.ts:5:83)
    at execMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
    at /home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/components/ofMapper.ts:7:22 {
  name: 'INJECTION_ERROR',
  tokens: [ Symbol(UsersSchema) ],
  origin: TypeError: Cannot read properties of undefined (reading 'isStore')
      at Function.from (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/domain/JsonEntityStore.ts:215:17)
      at getJsonEntityStore (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/utils/getJsonEntityStore.ts:34:26)
      at JsonLazyRef.get schema [as schema] (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/domain/JsonLazyRef.ts:16:30)
      at lazyRefMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/components/lazyRefMapper.ts:18:22)
      at execMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
      at anyMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/components/anyMapper.ts:13:22)
      at execMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
      at itemMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/components/itemMapper.ts:5:83)
      at execMapper (/home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
      at /home/shivansh/WebstormProjects/BlendtrixBackend/node_modules/@tsed/schema/src/components/ofMapper.ts:7:22
}
```

**Comment by Romakita** [comment]
Have you the same version for all @tsed dependencies. All integration test works. So the problem is on your side. Please give me a reproducible example.

**Comment by shivanshtalwar0** [comment]
Same code works on 6.112.0 but it throws mongoose NativeError that you
fixed in latest version. I am not sure why it is not working.

**Comment by shivanshtalwar0** [comment]
It says error is in JsonEntityStore.ts but this file doesnt exist

**Comment by shivanshtalwar0** [comment]
About working example i am not so sure what exactly is causing this exception to happen so i don't know what to share with you i only have access to project

**Comment by Romakita** [comment]
The .ts file is never embed in the npm module because the code is compiled. Ok so it's related to mongoose...

If you update the mongoose package?

**Comment by Romakita** [comment]
It's strange the code commit concern a problem about interface...
Your code works with v6.114.7 ?

**Comment by shivanshtalwar0** [comment]
I am running mongoose 6.3.3 and no it doesn't work on 6.114.7
It only works on 6.112.0 but on building using npm run build tsc throws NativeError from mongoose package that you fixed recently

**Comment by shivanshtalwar0** [comment]
I am kind of stuck neither upgrading or downgrading entirely fixes up the problem

**Comment by Romakita** [comment]
@shivanshtalwar0  Ok, It wasn't clear. So after 6.112.0, the project doesn't works. 

Have you tried intermediate version ? because the range between v6.112 and v6.114 is large (fix and feature).

**Comment by Romakita** [comment]
And again I haven't issue on other projects and your stack trace doesn't help, If you are not able to localize the origin of this issue  (Service/Middleware/Controller/Models).

The problem seems to be related to a decorator that use a:
```
anyOf
allOf
oneOf
```

**Comment by Romakita** [comment]
Hello @shivanshtalwar0 
Have you found the root cause ?

If not, you can contact me on slack :)
See you
Romain

**Comment by shivanshtalwar0** [comment]
> And again I haven't issue on other projects and your stack trace doesn't help, If you are not able to localize the origin of this issue (Service/Middleware/Controller/Models).
> 
> The problem seems to be related to a decorator that use a:
> 
> ```
> anyOf
> allOf
> oneOf
> ```

:( still couldn't trace down real issue as i have not used any of these it would be nice to connect on slack and show you via codeshare

**Comment by shivanshtalwar0** [comment]
please share your skype or slack id so I can connect with you at suitable time.

**Comment by shivanshtalwar0** [comment]
also if it interests you i have replicated the bug in brand new project just by copy-pasting few files over here's the repo for you to dig into https://github.com/shivanshtalwar0/tsed-bug-tracing

**Comment by Romakita** [comment]
https://api.tsed.io/rest/slack/tsedio/tsed

**Comment by Romakita** [comment]
Perfect. I take a time to look the problem :)

**Comment by Romakita** [comment]
Ok you have a circular reference between UserModel and StoreModel. It certainly not related to the [v6.114.8](https://github.com/tsedio/tsed/releases/tag/v6.114.8). 

I think you haven't tested versions between v6.112.3 and v6.114.8... But I don't know what the version responsible of this bug.

I'll add a pre check to avoid undefined model when the `@Ref` decorator is used and emit message to explain the problem.

See you
Romain

**Comment by shivanshtalwar0** [comment]
I have tried v6.114 and v6.113 problem persist in both of them i will try to resolve circular dependency and try if that works earlier this wasn't the issue but i don't know what introduced this bug

**Comment by Romakita** [comment]
ok so it's between v6.112.0 and v6.113.0. 

The PR is ready to be released :)

**Comment by shivanshtalwar0** [comment]
Thank you very much bro for quick resolution ❤️
