### ISSUE TITLE
[BUG] ERR_UNSUPPORTED_ESM_URL_SCHEME

### ISSUE THREAD

**Issue by sawa-ko** [TypedProject/ts-express-decorators#2054]
## Information

- **Version:** 6.128.3
- Packages:

		"@tsed/common": "^6.128.3",
		"@tsed/core": "^6.128.3",
		"@tsed/di": "^6.128.3",
		"@tsed/exceptions": "^6.128.3",
		"@tsed/platform-express": "^6.128.3",
		"@tsed/schema": "^6.128.3",

I am trying to use tsed with ESM but I get the following error. I am compiling with SWC. This is my SWC configuration.

```json
{
	"sourceMaps": true,
	"jsc": {
		"keepClassNames": true,
		"target": "es2022",
		"parser": {
			"syntax": "typescript",
			"decorators": true,
			"dynamicImport": true
		},
		"transform": {
			"legacyDecorator": true,
			"decoratorMetadata": true
		}
	},
	"module": {
		"type": "es6"
	}
}
```

## Example

```ts
import { Configuration, Inject, PlatformApplication } from '@tsed/common';

import { envParseNumber } from '@skyra/env-utilities';
import { fileURLToPath } from 'node:url';

@Configuration({
	mount: {
		'/': [fileURLToPath(new URL('./controllers/**/*.js', import.meta.url))]
	},
	httpPort: envParseNumber('APP_API_PORT'),
	acceptMimes: ['application/json'],
	logger: {
		logRequest: false,
		requestFields: ['reqId', 'method', 'url', 'query', 'params', 'duration']
	}
})
export class Server {
	@Inject()
	public app!: PlatformApplication;
}
```

## Error: 
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'
    at __node_internal_captureLargerStackTrace (node:internal/errors:477:5)
    at new NodeError (node:internal/errors:387:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1075:11)        
    at defaultResolve (node:internal/modules/esm/resolve:1155:3)
    at nextResolve (node:internal/modules/esm/loader:173:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
    at ESMLoader.import (node:internal/modules/esm/loader:536:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)       
    at loaderFn (E:\Proyectos\Equipos\Naeko\discord-bot\node_modules\@tsed\core\src\utils\imports\importPackage.ts:1:85)
    at importPackage (E:\Proyectos\Equipos\Naeko\discord-bot\node_modules\@tsed\core\src\utils\imports\importPackage.ts:3:18)
    at importFiles (E:\Proyectos\Equipos\Naeko\discord-bot\node_modules\@tsed\components-scan\src\importFiles.ts:13:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     
    at resolveRecursively (E:\Proyectos\Equipos\Naeko\discord-bot\node_modules\@tsed\components-scan\src\importProviders.ts:10:22)
    at <anonymous> (E:\Proyectos\Equipos\Naeko\discord-bot\node_modules\@tsed\components-scan\src\importProviders.ts:43:26)
    at async Promise.all (index 0)
    at importProviders (E:\Proyectos\Equipos\Naeko\discord-bot\node_modules\@tsed\components-scan\src\importProviders.ts:46:9)
    at Function.bootstrap (E:\Proyectos\Equipos\Naeko\discord-bot\node_modules\@tsed\common\src\builder\PlatformBuilder.ts:139:7)
    at NaekoClient.start (E:\Proyectos\Equipos\Naeko\discord-bot\src\lib\client.ts:111:22)
    at app (E:\Proyectos\Equipos\Naeko\discord-bot\src\main.ts:5:2)
    at <anonymous> (E:\Proyectos\Equipos\Naeko\discord-bot\src\main.ts:8:1) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v18.6.0
```

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Create a reproducible repository example. If I haven't that, I'll close this issue tomorrow !

**Comment by Romakita** [comment]
My advice also

Don't use globPatterns it's always a pain point with ESM. Import manually the modules. The Ts.ED CLI use barrelsby to general barrels files "index.ts".  (unfortunately barrelsby doesn't support esm module but it will a PR and issue are open).

v7 won't support glob patterns to import module. So don't use it  and your problem will be solved

See you

**Comment by Romakita** [comment]
It's incorrect to do that:

'/': [fileURLToPath(new URL('./controllers/**/*.js', import.meta.url))]

**Comment by sawa-ko** [comment]
Oh, ok.
To fix it I had to import the classes manually.

**Comment by Romakita** [comment]
It's one of the solution yes :)
