### ISSUE TITLE
[BUG] json-mapper BigInt deserialization fails when using Prisma

### ISSUE THREAD

**Issue by borjapazr** [TypedProject/ts-express-decorators#2099]
If a `Prisma schema` is defined and a `BigInt` type is used for, for example, the identifier of the primary key of a model, when retrieving and deserializing those elements through the repository that auto-generates Ts.ED, it fails due to the following error:

```
[2022-09-24 12:15:36.1536] ERROR ❌ BigInt is not a constructor TypeError: BigInt is not a constructor
    at new BigInt (<anonymous>)
    at plainObjectToClass (/Users/borja/Projects/personal/app_skeletons/express-typescript-skeleton/node_modules/@tsed/json-mapper/src/utils/deserialize.ts:140:20)
    at deserialize (/Users/borja/Projects/personal/app_skeletons/express-typescript-skeleton/node_modules/@tsed/json-mapper/src/utils/deserialize.ts:245:10)
    at /Users/borja/Projects/personal/app_skeletons/express-typescript-skeleton/node_modules/@tsed/json-mapper/src/utils/deserialize.ts:157:13
    at Map.forEach (<anonymous>)
    at plainObjectToClass (/Users/borja/Projects/personal/app_skeletons/express-typescript-skeleton/node_modules/@tsed/json-mapper/src/utils/deserialize.ts:142:17)
    at deserialize (/Users/borja/Projects/personal/app_skeletons/express-typescript-skeleton/node_modules/@tsed/json-mapper/src/utils/deserialize.ts:245:10)
    at JsonMapperContext.next [as _next] (/Users/borja/Projects/personal/app_skeletons/express-typescript-skeleton/node_modules/@tsed/json-mapper/src/utils/deserialize.ts:65:51)
    at JsonMapperContext.next (/Users/borja/Projects/personal/app_skeletons/express-typescript-skeleton/node_modules/@tsed/json-mapper/src/domain/JsonMapperContext.ts:27:17)
    at /Users/borja/Projects/personal/app_skeletons/express-typescript-skeleton/node_modules/@tsed/json-mapper/src/components/ArrayMapper.ts:12:50
```

It looks like `json-mapper` is trying to create a BigInt using the following syntax:

```
new BigInt(1n) // Uncaught TypeError: BigInt is not a constructor
```

This is the `Prisma schema` I am using:

```
model User {
  id            BigInt    @id @default(autoincrement())
  uuid          String    @unique @db.VarChar(1000)
  gender        Gender    @default(UNDEFINED)
  firstName     String    @db.VarChar(255)
  lastName      String    @db.VarChar(500)
  birthDate     DateTime  @db.Date
  username      String    @unique @db.VarChar(100)
  email         String    @unique @db.VarChar(255)
  phoneNumber   String    @db.VarChar(100)
  address       String    @db.VarChar(1500)
  profilePicUrl String    @db.VarChar(2500)
  password      String    @db.VarChar(100)
  verified      Boolean   @default(false)
  enabled       Boolean   @default(true)
  role          Role      @default(USER)
  sessions      Session[]
  createdAt     DateTime? @default(now()) @db.DateTime(6)
  createdBy     String?   @db.VarChar(255)
  updatedAt     DateTime? @default(now()) @updatedAt @db.DateTime(6)
  updatedBy     String?   @db.VarChar(255)
  deletedAt     DateTime? @db.DateTime(6)
  deletedBy     String?   @db.VarChar(255)
}
```

And this is the call to the repository:

```
public async findAll(): Promise<User[]> {
  const users = await this.usersRepository.findMany();

  return users.map(UserMapper.toDomainModel);
}
```

 

## Information

- **Version:** 6.132.0
- Packages:

    ```
    "@tsed/ajv": "^6.132.0",
    "@tsed/common": "^6.132.0",
    "@tsed/components-scan": "^6.132.0",
    "@tsed/core": "^6.132.0",
    "@tsed/di": "^6.132.0",
    "@tsed/exceptions": "^6.132.0",
    "@tsed/json-mapper": "^6.132.0",
    "@tsed/platform-express": "^6.132.0",
    "@tsed/prisma": "^6.132.0",
    "@tsed/schema": "^6.132.0",
    "@tsed/swagger": "^6.132.0",
   ```

**Comment by Romakita** [comment]
Hello @borjapazr 

Thanks for the detailed issue. The fix is almost ready :)

See you
Romain
