### ISSUE TITLE
[BUG] OASv3 schema generation fails when model used in `@OneOf` has `kind` property 

### ISSUE THREAD

**Issue by denis-maiorov-brightsec** [TypedProject/ts-express-decorators#2413]
## Information

- **Version:** 7.34.3 — 7.34.6
- Packages: @tsed/schema

[Recent fix](https://github.com/tsedio/tsed/commit/d6f3e4ea962fd715d43450f1119b12617483ba39) causes @OneOf to throw runtime error on swagger schema generation when one of the model properties name is `kind`

## Example

```ts
export enum Discriminator {
  ONE = 'one',
  TWO = 'two',
}

export abstract class BaseModel {
  @Enum(Discriminator.ONE, Discriminator.TWO)
  @DiscriminatorKey()
  public type!: Discriminator.ONE | Discriminator.TWO;
}

@DiscriminatorValue(Discriminator.ONE)
export class FirstImpl extends BaseModel {
  public override type!: Discriminator.ONE;

  @Enum('json')
  public kind!: 'json';
}

@DiscriminatorValue(Discriminator.TWO)
export class SecondImpl extends BaseModel {
  public override type!: Discriminator.TWO;
  
  @Property()
  public prop!: string;
}

export class ParentModel {
  @OneOf(FirstImpl, SecondImpl)
  public test?:
    | FirstImpl
    | SecondImpl;
}

@Controller('/test')
@Docs('api-v2')
@Name('Test')
export class TestController {

  @Get()
  @Returns(200, Array).Of(ParentModel)
  public get(): Promise<ParentModel> {
    return;
  }
}
```

## Trace
```
TypeError: input.entries is not a function
    at mapMapper (/Users/domayorov/brightsec/project/node_modules/@tsed/schema/src/components/mapMapper.ts:18:6)
    at execMapper (/Users/domayorov/brightsec/project/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
    at anyMapper (/Users/domayorov/brightsec/project/node_modules/@tsed/schema/src/components/anyMapper.ts:25:30)
    at execMapper (/Users/domayorov/brightsec/project/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
    at propertiesMapper (/Users/domayorov/brightsec/project/node_modules/@tsed/schema/src/components/propertiesMapper.ts:10:20)
    at execMapper (/Users/domayorov/brightsec/project/node_modules/@tsed/schema/src/registries/JsonSchemaMapperContainer.ts:35:35)
    at /Users/domayorov/brightsec/project/node_modules/@tsed/schema/src/components/schemaMapper.ts:95:27
    at Array.reduce (<anonymous>)
```

## Acceptance criteria

- [ ] Swagger generation works

**Comment by Romakita** [comment]
@denis-maiorov-brightsec Thanks for the detailed issue :D

The fix is almost done!
