### ISSUE TITLE
[BUG] jsonMapper compilation failed if model has properties with name equal to reserved keyword (example: enum)

### ISSUE THREAD

**Issue by Bugslive** [TypedProject/ts-express-decorators#2448]
### Describe the bug

Following v7.36 release, the new jsonMapper compilation failed if property name of the model are equal to reserved keyword

```
[2023-09-27T16:06:49.479] [ERROR] [TSED] - {
  method: 'GET',
  url: '/test/failed',
  route: '/test/failed',
  headers: {
    host: 'localhost:8083',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0',
    accept: 'application/json',
    'accept-language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3',
    'accept-encoding': 'gzip, deflate, br',
    dnt: '1',
    connection: 'keep-alive',
    cookie: '_pk_id.1.1fff=b1f543f220c17ea0.1689800215.',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin'
  },
  body: {},
  query: {},
  params: {},
  reqId: '35313dbaf326466488c91321b5709fc1',
  time: 2023-09-27T14:06:49.479Z,
  duration: 42,
  event: 'request.end',
  status: 500,
  status_code: '500',
  state: 'KO',
  error_name: 'Error',
  error_message: 'Fail to compile mapper for TestModel. See the error above: Unexpected strict mode reserved word.
' +
    '(input,options) => {
' +
    '  if (isNil(input)) {
' +
    '    return input;
' +
    '  }
' +
    '  const obj = {};
' +
    '  options = {...options, self: input};
' +
    '  if (input && isCollection(input)) {
' +
    "    return execMapper(nameOf(classOf(input)), input, {...options, id: 'TestModel:eebzbch:default'});
" +
    '  }
' +
    '  if (hasJsonMethod(input)) {
' +
    "    return mapJSON(input, {...options, id: 'TestModel:eebzbch:default'});
" +
    '  }
' +
    '  // Map type TestModel:eebzbch:default 
' +
    '  let type = input.type;
' +
    '  if (type !== undefined) {
' +
    "    type = execMapper('String', type, options);
" +
    '    obj.type = type;
' +
    '  }
' +
    '  // Map enum TestModel:eebzbch:default 
' +
    '  let enum = input.enum;
' +
    '  if (enum !== undefined) {
' +
    "    enum = execMapper('Array', enum, { ...options, id: 'Object' });
" +
    '    obj.enum = enum;
' +
    '  }
' +
    '  // Map default TestModel:eebzbch:default 
' +
    '  let default = input.default;
' +
    '  if (default !== undefined) {
' +
    "    default = execMapper('String', default, options);
" +
    '    obj.default = default;
' +
    '  }
' +
    '  // Map name TestModel:eebzbch:default 
' +
    '  let name = input.name;
' +
    '  if (name !== undefined) {
' +
    "    name = execMapper('String', name, options);
" +
    '    obj.name = name;
' +
    '  }
' +
    '  // Map description TestModel:eebzbch:default 
' +
    '  let description = input.description;
' +
    '  if (description !== undefined) {
' +
    "    description = execMapper('String', description, options);
" +
    '    obj.description = description;
' +
    '  }
' +
    '  return obj;
' +
    '}',
  error_stack: 'Error: Fail to compile mapper for TestModel. See the error above: Unexpected strict mode reserved word.
' +
    '(input,options) => {
' +
    '  if (isNil(input)) {
' +
    '    return input;
' +
    '  }
' +
    '  const obj = {};
' +
    '  options = {...options, self: input};
' +
    '  if (input && isCollection(input)) {
' +
    "    return execMapper(nameOf(classOf(input)), input, {...options, id: 'TestModel:eebzbch:default'});
" +
    '  }
' +
    '  if (hasJsonMethod(input)) {
' +
    "    return mapJSON(input, {...options, id: 'TestModel:eebzbch:default'});
" +
    '  }
' +
    '  // Map type TestModel:eebzbch:default 
' +
    '  let type = input.type;
' +
    '  if (type !== undefined) {
' +
    "    type = execMapper('String', type, options);
" +
    '    obj.type = type;
' +
    '  }
' +
    '  // Map enum TestModel:eebzbch:default 
' +
    '  let enum = input.enum;
' +
    '  if (enum !== undefined) {
' +
    "    enum = execMapper('Array', enum, { ...options, id: 'Object' });
" +
    '    obj.enum = enum;
' +
    '  }
' +
    '  // Map default TestModel:eebzbch:default 
' +
    '  let default = input.default;
' +
    '  if (default !== undefined) {
' +
    "    default = execMapper('String', default, options);
" +
    '    obj.default = default;
' +
    '  }
' +
    '  // Map name TestModel:eebzbch:default 
' +
    '  let name = input.name;
' +
    '  if (name !== undefined) {
' +
    "    name = execMapper('String', name, options);
" +
    '    obj.name = name;
' +
    '  }
' +
    '  // Map description TestModel:eebzbch:default 
' +
    '  let description = input.description;
' +
    '  if (description !== undefined) {
' +
    "    description = execMapper('String', description, options);
" +
    '    obj.description = description;
' +
    '  }
' +
    '  return obj;
' +
    '}
' +
    '    at JsonSerializer.compile (/Users/workspace/test7.36/node_modules/@tsed/json-mapper/src/domain/JsonMapperCompiler.ts:168:15)
' +
    '    at JsonSerializer.map (/Users/workspace/test7.36/node_modules/@tsed/json-mapper/src/domain/JsonSerializer.ts:60:25)
' +
    '    at serialize (/Users/workspace/test7.36/node_modules/@tsed/json-mapper/src/utils/serialize.ts:11:21)
' +
    '    at PlatformResponseFilter.serialize (/Users/workspace/test7.36/node_modules/@tsed/platform-response-filter/src/services/PlatformResponseFilter.ts:92:25)
' +
    '    at PlatformHandler.flush (/Users/workspace/test7.36/node_modules/@tsed/common/src/services/PlatformHandler.ts:98:44)
' +
    '    at /Users/workspace/test7.36/node_modules/@tsed/common/src/services/PlatformHandler.ts:184:51
' +
    '    at catchAsyncError (/Users/workspace/test7.36/node_modules/@tsed/core/src/utils/catchError.ts:11:11)
' +
    '    at PlatformHandler.onFinish (/Users/workspace/test7.36/node_modules/@tsed/common/src/services/PlatformHandler.ts:184:39)
' +
    '    at /Users/workspace/test7.36/node_modules/@tsed/platform-express/src/components/PlatformExpress.ts:152:13
' +
    '    at runInContext (/Users/workspace/test7.36/node_modules/@tsed/di/src/node/utils/asyncHookContext.ts:24:12)'
}
```

### To Reproduce

1. Clone https://github.com/Bugslive/tsed-7.36.git
2. run 'npm run build'
3. run 'npm start'
4. Perform GET http://localhost:8083/test => 200 OK
5. Perform GET http://localhost:8083/test/failed => 500 KO

### Expected behavior

Ts.ED jsonMapper should retrieve v7.35 behaviour and accept to serialize/deserialize json with this kind of property name. 

### Code snippets

```
[2023-09-27T16:06:49.479] [ERROR] [TSED] - {
  method: 'GET',
  url: '/test/failed',
  route: '/test/failed',
  headers: {
    host: 'localhost:8083',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0',
    accept: 'application/json',
    'accept-language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3',
    'accept-encoding': 'gzip, deflate, br',
    dnt: '1',
    connection: 'keep-alive',
    cookie: '_pk_id.1.1fff=b1f543f220c17ea0.1689800215.',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin'
  },
  body: {},
  query: {},
  params: {},
  reqId: '35313dbaf326466488c91321b5709fc1',
  time: 2023-09-27T14:06:49.479Z,
  duration: 42,
  event: 'request.end',
  status: 500,
  status_code: '500',
  state: 'KO',
  error_name: 'Error',
  error_message: 'Fail to compile mapper for TestModel. See the error above: Unexpected strict mode reserved word.
' +
    '(input,options) => {
' +
    '  if (isNil(input)) {
' +
    '    return input;
' +
    '  }
' +
    '  const obj = {};
' +
    '  options = {...options, self: input};
' +
    '  if (input && isCollection(input)) {
' +
    "    return execMapper(nameOf(classOf(input)), input, {...options, id: 'TestModel:eebzbch:default'});
" +
    '  }
' +
    '  if (hasJsonMethod(input)) {
' +
    "    return mapJSON(input, {...options, id: 'TestModel:eebzbch:default'});
" +
    '  }
' +
    '  // Map type TestModel:eebzbch:default 
' +
    '  let type = input.type;
' +
    '  if (type !== undefined) {
' +
    "    type = execMapper('String', type, options);
" +
    '    obj.type = type;
' +
    '  }
' +
    '  // Map enum TestModel:eebzbch:default 
' +
    '  let enum = input.enum;
' +
    '  if (enum !== undefined) {
' +
    "    enum = execMapper('Array', enum, { ...options, id: 'Object' });
" +
    '    obj.enum = enum;
' +
    '  }
' +
    '  // Map default TestModel:eebzbch:default 
' +
    '  let default = input.default;
' +
    '  if (default !== undefined) {
' +
    "    default = execMapper('String', default, options);
" +
    '    obj.default = default;
' +
    '  }
' +
    '  // Map name TestModel:eebzbch:default 
' +
    '  let name = input.name;
' +
    '  if (name !== undefined) {
' +
    "    name = execMapper('String', name, options);
" +
    '    obj.name = name;
' +
    '  }
' +
    '  // Map description TestModel:eebzbch:default 
' +
    '  let description = input.description;
' +
    '  if (description !== undefined) {
' +
    "    description = execMapper('String', description, options);
" +
    '    obj.description = description;
' +
    '  }
' +
    '  return obj;
' +
    '}',
  error_stack: 'Error: Fail to compile mapper for TestModel. See the error above: Unexpected strict mode reserved word.
' +
    '(input,options) => {
' +
    '  if (isNil(input)) {
' +
    '    return input;
' +
    '  }
' +
    '  const obj = {};
' +
    '  options = {...options, self: input};
' +
    '  if (input && isCollection(input)) {
' +
    "    return execMapper(nameOf(classOf(input)), input, {...options, id: 'TestModel:eebzbch:default'});
" +
    '  }
' +
    '  if (hasJsonMethod(input)) {
' +
    "    return mapJSON(input, {...options, id: 'TestModel:eebzbch:default'});
" +
    '  }
' +
    '  // Map type TestModel:eebzbch:default 
' +
    '  let type = input.type;
' +
    '  if (type !== undefined) {
' +
    "    type = execMapper('String', type, options);
" +
    '    obj.type = type;
' +
    '  }
' +
    '  // Map enum TestModel:eebzbch:default 
' +
    '  let enum = input.enum;
' +
    '  if (enum !== undefined) {
' +
    "    enum = execMapper('Array', enum, { ...options, id: 'Object' });
" +
    '    obj.enum = enum;
' +
    '  }
' +
    '  // Map default TestModel:eebzbch:default 
' +
    '  let default = input.default;
' +
    '  if (default !== undefined) {
' +
    "    default = execMapper('String', default, options);
" +
    '    obj.default = default;
' +
    '  }
' +
    '  // Map name TestModel:eebzbch:default 
' +
    '  let name = input.name;
' +
    '  if (name !== undefined) {
' +
    "    name = execMapper('String', name, options);
" +
    '    obj.name = name;
' +
    '  }
' +
    '  // Map description TestModel:eebzbch:default 
' +
    '  let description = input.description;
' +
    '  if (description !== undefined) {
' +
    "    description = execMapper('String', description, options);
" +
    '    obj.description = description;
' +
    '  }
' +
    '  return obj;
' +
    '}
' +
    '    at JsonSerializer.compile (/Users/vincent/workspace/test7.36/node_modules/@tsed/json-mapper/src/domain/JsonMapperCompiler.ts:168:15)
' +
    '    at JsonSerializer.map (/Users/vincent/workspace/test7.36/node_modules/@tsed/json-mapper/src/domain/JsonSerializer.ts:60:25)
' +
    '    at serialize (/Users/vincent/workspace/test7.36/node_modules/@tsed/json-mapper/src/utils/serialize.ts:11:21)
' +
    '    at PlatformResponseFilter.serialize (/Users/vincent/workspace/test7.36/node_modules/@tsed/platform-response-filter/src/services/PlatformResponseFilter.ts:92:25)
' +
    '    at PlatformHandler.flush (/Users/vincent/workspace/test7.36/node_modules/@tsed/common/src/services/PlatformHandler.ts:98:44)
' +
    '    at /Users/vincent/workspace/test7.36/node_modules/@tsed/common/src/services/PlatformHandler.ts:184:51
' +
    '    at catchAsyncError (/Users/vincent/workspace/test7.36/node_modules/@tsed/core/src/utils/catchError.ts:11:11)
' +
    '    at PlatformHandler.onFinish (/Users/vincent/workspace/test7.36/node_modules/@tsed/common/src/services/PlatformHandler.ts:184:39)
' +
    '    at /Users/vincent/workspace/test7.36/node_modules/@tsed/platform-express/src/components/PlatformExpress.ts:152:13
' +
    '    at runInContext (/Users/vincent/workspace/test7.36/node_modules/@tsed/di/src/node/utils/asyncHookContext.ts:24:12)'
}
```

### Repository URL example

https://github.com/Bugslive/tsed-7.36.git

### OS

macOS

### Node version

Node v16.20.2

### Library version

v7.36.x

**Comment by Romakita** [comment]
ok I see.

I'll fix that immediately :)

**Comment by Romakita** [comment]
https://github.com/tsedio/tsed/pull/2449

**Comment by Bugslive** [comment]
Hi Romain,
Something goes wrong in dependy resolution with the new release 7.36.4.
You can find 2 log files in attachment:

- npm-update.log: log from CMD "npm update" for the project I used for this issue.
- npm-install.log: log from CMD "npm install" for a newly created project.

Hope this helps

[npm-install.log](https://github.com/tsedio/tsed/files/12747293/npm-install.log)
[npm-update.log](https://github.com/tsedio/tsed/files/12747294/npm-update.log)

**Comment by Romakita** [comment]
Arf some packages are missing on NPM... I'll try to republish version
