### ISSUE TITLE
[BUG] `UsePipe` makes decorator test fail

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2514]
### Describe the bug

According to #2512 i just implemented a pipe to kind of set a default value for a decorated value, which works great in my app. 

**But** i just noticed it breaks by test for my decorator and i could recreate this in a starter project quite easy, so see reproduction attached below.

I created a keyword, a pipe and a function to combine them in a custom decorator:

```ts
import { AjvDataValidateFunction, Keyword, KeywordMethods } from '@tsed/ajv';
import { CustomKey, PipeMethods } from '@tsed/schema';
import { useDecorators } from '@tsed/core';
import { UsePipe } from '@tsed/platform-params';
import { Injectable } from '@tsed/di';

@Keyword({
  keyword: 'my-decorator',
  type: 'string'
})
export class MyDecoratorKeyword implements KeywordMethods {
  compile(): AjvDataValidateFunction {
    return (value: string) => !value.startsWith('invalid');
  }
}

@Injectable()
class MyDecoratorPipe implements PipeMethods<string, string> {
  transform(value: string): string {
    if (!value) {
      value = 'default';
    }
    return value;
  }
}

export function MyDecorator() {
  return useDecorators(
    CustomKey('my-decorator', null),
    UsePipe(MyDecoratorPipe)
  );
}
```

In my test this causes:

```

  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'push')

       6 | class Test {
       7 |   @MyDecorator()
    >  8 |   key: string;
         |   ^
       9 | }
      10 |
      11 | describe('MyDecorator Keyword', () => {

      at node_modules/@tsed/platform-params/src/decorators/usePipe.ts:18:17
      at node_modules/@tsed/schema/src/decorators/common/jsonEntityFn.ts:27:25
      at node_modules/@tsed/core/src/utils/decorators/useDecorators.ts:9:9
          at Array.forEach (<anonymous>)
      at node_modules/@tsed/core/src/utils/decorators/useDecorators.ts:8:8
      at DecorateProperty (node_modules/reflect-metadata/Reflect.js:553:33)
      at Reflect.decorate (node_modules/reflect-metadata/Reflect.js:123:24)
      at Object.__decorate (node_modules/tslib/tslib.js:105:96)
      at Object.<anonymous> (src/decorators/my-decorator/my-decorator.keyword.test.ts:8:3)

```

### To Reproduce

1. Fetch Repo: https://github.com/EinfachHans/tsed-pipe-test
2. Run test: `src/decorators/my-decorator/my-decorator.keyword.test.ts`

### Expected behavior

Not to fail i would say? 😃 

### OS

macOs

### Node version

18.17.1

### Library version

7.43.0

**Comment by Romakita** [comment]
But your example is wrong... UsePipe cannot be used on property... It's Parameter decorator!

**Comment by Romakita** [comment]
You've completely misunderstood my comment in this issue #1605 2512.

I said you, you cannot use a Model on HeaderParams, because it's always a string and use deserialization is not possible (not recommended in fact), but the correct solution is to use Pipe to do that:

```ts
@Controller('/')
class MyController {
  @Get("/")
  get(@HeaderParams("x-custom-header") @UsePipe(MyPipe) header: string) {} 
}
```

If your goal is to implement a validation for this header, you can create a custom decorator with a specific JsonSchema:

```ts
import {string} from "@tsed/schema";

const headerSchema = string().minLength(3).customKey("custom-key");

@Injectable()
class DefaultPipe implements PipeMethods<string, string> { // but if ajv cast value, maybe ajv have an option to set default value from the json-schema ?
  transform(value: string, entity: JsonParameterStore): string {
    if (!value) {
      value = entity.itemSchema.get('default');
    }
    return value;
  }
}


export function XCustomHeader({default: value}: {default: string}) {
  return useDecorators(
     @HeaderParams("x-custom-header"),
     @Schema(headerSchema.default(value)),
     value != undefined && @UsePipe(DefaultPipe)
  ) 
}
```
See you

**Comment by Romakita** [comment]
https://ajv.js.org/options.html => useDefaults so no pipe required in this case ^^

**Comment by EinfachHans** [comment]
Yeah that is what i did, but my test was wrong then, thanks again for your explanation 👍🏼
