### ISSUE TITLE
[BUG] Error while launching the app after initialization Error: Cannot find module '@tsed/passportjs'

### ISSUE THREAD

**Issue by midoelhawy** [TypedProject/ts-express-decorators#2542]
### Describe the bug

**Error Launching App After Initialization**

I encountered an error while attempting to launch the application following initialization with `tsed init .`. The error message is as follows:

```
For help, see: https://nodejs.org/en/docs/inspector
Error: Cannot find module '@tsed/passportjs'
Require stack:
- /tmp/xxx/src/Server.ts
- /tmp/xxx/src/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.Module._resolveFilename (/tmp/xxx/node_modules/tsconfig-paths/src/register.ts:115:36)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/tmp/xxx/src/Server.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._compile (/tmp/xxx/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-9617310348905903.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
[ERROR] 12:19:46 Error: Cannot find module '@tsed/passportjs'
Require stack:
- /tmp/xxx/src/Server.ts
- /tmp/xxx/src/index.ts
Child got SIGTERM, exiting.
```

Upon attempting to install the package, a conflict arose between the packages:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @tsed/testing-mongoose@7.50.0
npm ERR! Found: mongoose@8.0.2
npm ERR! node_modules/mongoose
npm ERR!   peer mongoose@">=6.0.0" from @tsed/mongoose@7.50.0
npm ERR!   node_modules/@tsed/mongoose
npm ERR!     peer @tsed/mongoose@"^7.50.0" from @tsed/testing-mongoose@7.50.0
npm ERR!     node_modules/@tsed/testing-mongoose
npm ERR!       dev @tsed/testing-mongoose@"^7.50.0" from the root project
npm ERR!     @tsed/mongoose@"^7.50.0" from the root project
npm ERR!   mongoose@"^8.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mongoose@"^6.1.7" from @tsed/testing-mongoose@7.50.0
npm ERR! node_modules/@tsed/testing-mongoose
npm ERR!   dev @tsed/testing-mongoose@"^7.50.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: mongoose@6.12.3
npm ERR! node_modules/mongoose
npm ERR!   peer mongoose@"^6.1.7" from @tsed/testing-mongoose@7.50.0
npm ERR!   node_modules/@tsed/testing-mongoose
npm ERR!     dev @tsed/testing-mongoose@"^7.50.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR!
```

### To Reproduce

 RUN `tsed init .`

-      Choose the target platform: expressjs
-      Choose the architecture for your project: Ts.ED 
-      Choose the convention file styling: Ts.ED
-      Check the features needed for your project : Database, Passport.js, Swagger
-      Choose a ORM manager: Mongoose
-      Choose the package manager: NPM

### Expected behavior

I expect the correct launch without any error exception  

### OS

UBUNTU 22.04

### Node version

NODE v20.9.0

### Library version

^7.50.0

**Comment by midoelhawy** [comment]
hi @Romakita 
any news about the bug ?

**Comment by Romakita** [comment]
install the @tsed/passport to your project should solve your issue :)

**Comment by Romakita** [comment]
You can use -f option of npm command also

**Comment by Romakita** [comment]
And making small PR to fix that is also welcome @midoelhawy  ;)
