### ISSUE TITLE
[BUG] Inject interface using `Injectable` does not work

### ISSUE THREAD

**Issue by jonatasdaniel** [TypedProject/ts-express-decorators#2545]
### Describe the bug

Hey,

I'm using DDD approach with Tsed, so for every repository interface (which belongs to my domain layer) I have a implementation (which belongs to infra layer).
So on my services (domain layer as well) I want to inject my repositories, but I'm expecting the interface in service constructor. But that's not working to me.
When I start my app, I get this error:

```
{
  event: 'SERVER_BOOTSTRAP_ERROR',
  message: 'Injection failed on LanguagesController > LanguageService\n' +
    "Origin: Unable to inject dependency. Cannot read properties of undefined (reading 'prototype')\n" +
    '\n' +
    'LanguageService->constructor(\x1B[31mrepository\x1B[39m: LanguageRepository)\n' +
    '                             \x1B[31m^‾‾‾‾‾‾‾‾‾\x1B[39m',
  stack: 'INJECTION_ERROR: Injection failed on LanguagesController > LanguageService\n' +
    "Origin: Unable to inject dependency. Cannot read properties of undefined (reading 'prototype')\n" +
    '\n' +
    'LanguageService->constructor(\x1B[31mrepository\x1B[39m: LanguageRepository)\n' +
    '                             \x1B[31m^‾‾‾‾‾‾‾‾‾\x1B[39m\n' +
    '    at Function.throwInjectorError (/Users/jonatasdaniel/Dev/project/api/node_modules/.pnpm/@tsed+di@7.48.0_@tsed+core@7.48.0_@tsed+logger@6.6.3_@tsed+schema@7.48.0/node_modules/@tsed/di/src/common/errors/InjectionError.ts:44:11)\n' +
    '    at InjectorService.resolve (/Users/jonatasdaniel/Dev/project/api/node_modules/.pnpm/@tsed+di@7.48.0_@tsed+core@7.48.0_@tsed+logger@6.6.3_@tsed+schema@7.48.0/node_modules/@tsed/di/src/common/services/InjectorService.ts:641:22)\n' +
    '    at InjectorService.invoke (/Users/jonatasdaniel/Dev/project/api/node_modules/.pnpm/@tsed+di@7.48.0_@tsed+core@7.48.0_@tsed+logger@6.6.3_@tsed+schema@7.48.0/node_modules/@tsed/di/src/common/services/InjectorService.ts:212:21)\n' +
    '    at InjectorService.loadSync (/Users/jonatasdaniel/Dev/project/api/node_modules/.pnpm/@tsed+di@7.48.0_@tsed+core@7.48.0_@tsed+logger@6.6.3_@tsed+schema@7.48.0/node_modules/@tsed/di/src/common/services/InjectorService.ts:265:14)\n' +
    '    at InjectorService.load (/Users/jonatasdaniel/Dev/project/api/node_modules/.pnpm/@tsed+di@7.48.0_@tsed+core@7.48.0_@tsed+logger@6.6.3_@tsed+schema@7.48.0/node_modules/@tsed/di/src/common/services/InjectorService.ts:337:10)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at PlatformBuilder.loadInjector (/Users/jonatasdaniel/Dev/project/api/node_modules/.pnpm/@tsed+common@7.48.0_@tsed+engines@7.48.0_@tsed+logger-file@6.6.3_@tsed+logger@6.6.3_@tsed+openspec@7.48.0/node_modules/@tsed/common/src/builder/PlatformBuilder.ts:200:5)\n' +
    '    at PlatformBuilder.runLifecycle (/Users/jonatasdaniel/Dev/project/api/node_modules/.pnpm/@tsed+common@7.48.0_@tsed+engines@7.48.0_@tsed+logger-file@6.6.3_@tsed+logger@6.6.3_@tsed+openspec@7.48.0/node_modules/@tsed/common/src/builder/PlatformBuilder.ts:187:5)\n' +
    '    at bootstrap (/Users/jonatasdaniel/Dev/project/api/src/index.ts:7:22)'
}
```

Am I doing something wrong or that's an issue?

### To Reproduce

```ts
// languages.controller.ts

import LanguageService from "@domain/language/language.service";
import { Controller } from "@tsed/di";

@Controller("/v1/languages")
export class LanguagesController {
  constructor(private readonly languageService: LanguageService) {}
}

```

```ts
// language.service.ts

import { Inject } from "@tsed/di";
import LanguageRepository, {
  LanguageRepositoryKey,
} from "./language.repository";

export default class LanguageService {
  constructor(
    @Inject(LanguageRepositoryKey)
    private readonly repository: LanguageRepository
  ) {}
}
```
```ts
// language.repository.ts (my domain repository)

import BaseRepository from "@domain/shared/base.repository";
import { Language } from "./language.entity";

export default interface LanguageRepository extends BaseRepository<Language> {}

export const LanguageRepositoryKey: unique symbol =
  Symbol("LanguageRepository");
```
```ts
// language.pg.repository.ts (infra repository)

import { PostgresDataSource } from "./../data-source/PostgresDatasource";
import LanguageRepository, {
  LanguageRepositoryKey,
} from "@domain/language/language.repository";
import { Inject, Injectable } from "@tsed/di";
import { POSTGRES_DATA_SOURCE } from "../data-source/PostgresDatasource";
import { Language } from "@domain/language/language.entity";
import { LanguageEntitySchema } from "../schemas/language.schema";

@Injectable({ provide: LanguageRepositoryKey })
export default class LanguagePgRepository implements LanguageRepository {
  private repository;

  constructor(
    @Inject(POSTGRES_DATA_SOURCE) dataSource: typeof PostgresDataSource
  ) {
    this.repository = dataSource.getRepository<Language>(LanguageEntitySchema);
  }
}
```

### Expected behavior

Expect to inject repository implementation on my service class

### Repository URL example

[repo](https://github.com/jonatasdaniel/tsed-di-issue)

### OS

macOS

### Node version

Node v.18.6.0

### Library version

v7.48.0

**Comment by Romakita** [comment]
Hello @jonatasdaniel 
There is no reason to not works. There are many integration that cover this usecase. Please create reproducible repo example.

See you

**Comment by Romakita** [comment]
I suggest your to check if you haven't a circular reference between injectable class.

**Comment by jonatasdaniel** [comment]
@Romakita here is a repo to reproduce the issue
https://github.com/jonatasdaniel/tsed-di-issue

**Comment by Romakita** [comment]
Ok found error. You missed to import all code in infra in your server project. So the DI cannot discover the services that are attached to your domain.
Edit your barrelsby:

```json
{
  "directory": ["./src/rest","./src/pages","./src/infra"],
  "exclude": [
    "__mock__",
    "__mocks__",
    ".spec.ts"
  ],
  "delete": true
}

```
Then add the following line in your server.ts:

```ts
import { join } from "path";
import { Configuration, Inject } from "@tsed/di";
import { PlatformApplication } from "@tsed/common";
import "@tsed/platform-express"; // /!\ keep this import
import "@tsed/swagger";
import "./infra/index";  /// here
import { config } from "./config/index";
import * as rest from "./rest/index";
import * as pages from "./pages/index";
```
The DI works as expected (as I predicted XD)

See you ;)
