### ISSUE TITLE
[BUG]  TypeError: Cannot read properties of undefined (reading 'isDone')

### ISSUE THREAD

**Issue by DaniGTA** [TypedProject/ts-express-decorators#2712]
### Describe the bug

 Upgraded my project to version **7.69.4**
 
 TypeError: Cannot read properties of undefined (reading 'isDone')
     at file:///app/node_modules/@tsed/platform-express/lib/esm/components/PlatformExpress.js:71:19
     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
     at /app/node_modules/express/lib/router/index.js:286:9
     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
     at next (/app/node_modules/express/lib/router/index.js:280:10)
     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
     at /app/node_modules/express/lib/router/index.js:286:9
     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)

### To Reproduce

i use express with tsed.

"express": "^4.19.2",
"@tsed/common": "^7.69.4",
"@tsed/components-scan": "^7.69.4",
"@tsed/core": "^7.69.4",
"@tsed/di": "^7.69.4",
"@tsed/exceptions": "^7.69.4",
"@tsed/json-mapper": "^7.69.4",
"@tsed/platform-express": "^7.69.4",
"@tsed/schema": "^7.69.4",
"@tsed/socketio": "^7.69.4",

### Expected behavior

no undefined error from tsed.

### OS

Linux

### Node version

Node v21

### Library version

v7.69.4

**Comment by DaniGTA** [comment]
error is not related to tsed

**Comment by Romakita** [comment]
Please try latest version ^^.
See you
