### ISSUE TITLE
[BUG] TypeError in JsonDeserializer when handling Array of Maps

### ISSUE THREAD

**Issue by ochrstn** [TypedProject/ts-express-decorators#2761]
### Describe the bug

When using Ts.ED to handle an array of maps, a TypeError is thrown by the JsonDeserializer

### To Reproduce

```ts
import { Controller } from "@tsed/di";
import { BodyParams } from "@tsed/platform-params";
import { CollectionOf, Get, Post, Required } from "@tsed/schema";

class Test {
  @Required()
  @CollectionOf(Map<string, string>)
  fields: Array<Map<string, string>> = [];
}

@Controller("/hello-world")
export class HelloWorldController {
  @Post("/")
  post(@BodyParams() model: Test) {

    /*
    👎🏻 Throws:
    {
      "name": "TypeError",
      "message": "this.mappers[id] is not a function",
      "status": 500,
      "errors": [],
      "stack": "TypeError: this.mappers[id] is not a function\n    at JsonDeserializer.execMapper (/private/tmp/tsed-arrayofmaps/node_modules/@tsed/json-mapper/src/domain/JsonMapperCompiler.ts:187:28)\n    at JsonDeserializer.mapItem (/private/tmp/tsed-arrayofmaps/node_modules/@tsed/json-mapper/src/domain/JsonDeserializer.ts:391:17)\n    at /private/tmp/tsed-arrayofmaps/node_modules/@tsed/json-mapper/src/domain/JsonDeserializer.ts:384:25\n    at Array.forEach (<anonymous>)\n    at JsonDeserializer.mapMap (/private/tmp/tsed-arrayofmaps/node_modules/@tsed/json-mapper/src/domain/JsonDeserializer.ts:383:23)\n    at JsonDeserializer.execMapper (/private/tmp/tsed-arrayofmaps/node_modules/@tsed/json-mapper/src/domain/JsonMapperCompiler.ts:187:28)\n    at JsonDeserializer.mapItem (/private/tmp/tsed-arrayofmaps/node_modules/@tsed/json-mapper/src/domain/JsonDeserializer.ts:391:17)\n    at /private/tmp/tsed-arrayofmaps/node_modules/@tsed/json-mapper/src/domain/JsonDeserializer.ts:372:19\n    at Array.map (<anonymous>)\n    at JsonDeserializer.mapArray (/private/tmp/tsed-arrayofmaps/node_modules/@tsed/json-mapper/src/domain/JsonDeserializer.ts:371:29)"
    }
    */

    return model;
  }

  @Get("/")
  get() {
    const result = new Test();
    result.fields = [
      new Map(Object.entries({ de: "Deutsch", en: "English", fr: "Français" })),
      new Map(Object.entries({ es: "Español", it: "Italiano" })),
    ];
    return result;

    /*
    👍🏻  Returns:
    {
      "fields": [
          {
              "de": "Deutsch",
              "en": "English",
              "fr": "Français"
          },
          {
              "es": "Español",
              "it": "Italiano"
          }
      ]
    }
    */
  }
}
```

### Expected behavior

Should deserialize correctly

### OS

macOS

### Node version

v18.18.2

### Library version

7.77.0

**Comment by Romakita** [comment]
Hello @ochrstn 

I think your example isn't valid. Try that:

```ts

class Test {
  @Required()
  @CollectionOf(Map)
  fields: Array<Map<string, string>> = [];
}

```

See you

**Comment by ochrstn** [comment]
> Hello @ochrstn
> 
> I think your example isn't valid. Try that:
> 
> ```ts
> class Test {
>   @Required()
>   @CollectionOf(Map)
>   fields: Array<Map<string, string>> = [];
> }
> ```
> 
> See you

same problem

**Comment by Romakita** [comment]
So @ochrstn these usage isn't officially supported by tsed in fact, because describing an array of map of string (something else isn't possible with decorators).

I'll take a time to give you a workaround.
See you

**Comment by ochrstn** [comment]
> So @ochrstn these usage isn't officially supported by tsed in fact, because describing an array of map of string (something else isn't possible with decorators).
> 
> I'll take a time to give you a workaround. See you

Thanks for clarifying.

Thats my workaround so far:

```ts
@AdditionalProperties(true)
class Field {
  [key: string]: string;
}

class Test {
  @Required()
  @CollectionOf(Field)
  fields: Array<Field> = [];
}
```

This works for my usecase so far. Any additional ideas?

**Comment by Romakita** [comment]
Maybe this workaround should works:

```ts
    const schema = array().items(map().additionalProperties(String))

    class Test {
      @Schema(schema.toJSON())
      @CollectionOf(Map)
      @OnDeserialize(o => o.map((i) => new Map(Object.entries(i))))
      @OnSerialize(o => o.map(i => Object.fromEntries(i.entries())))
      fields: Map<string, string>[] = [];
    }
```

**Comment by Romakita** [comment]
But if you don't care about having an array of map:

```ts
const schema = array().items(object().additionalProperties(string()))

    class Test {
      @Schema(schema.toJSON())
      @CollectionOf(Object)
      fields: Record<string, string>[] = [];
    }
```

**Comment by Romakita** [comment]
@ochrstn This PR should improve the DX when you declare a Collection of Map:

https://github.com/tsedio/tsed/pull/2762
