### ISSUE TITLE
[ERROR] [TSED] - TypeError: Cannot read properties of undefined (reading 'paramType')

### ISSUE THREAD

**Issue by KarthikeyanPriyaGuhanMahi** [TypedProject/ts-express-decorators#2765]
### Describe the bug

> testcenter-api@2.68.0 serve
> cross-env-shell node --inspect dist/src/startup.js ./.env.dev

Debugger listening on ws://127.0.0.1:9229/d3f2fed7-a36d-4e6d-8466-8552e2bee8a2
For help, see: https://nodejs.org/en/docs/inspector
[2024-07-26T10:52:00.964] [DEBUG] [TSED] - Start server...
[2024-07-26T10:52:00.982] [INFO ] [TSED] - Loading EXPRESS platform adapter... +15ms
[2024-07-26T10:52:01.067] [INFO ] [TSED] - Injector created... +85ms
[2024-07-26T10:52:01.068] [INFO ] [TSED] - Build providers +1ms
[2024-07-26T10:52:01.109] [INFO ] [TSED] - Settings and injector loaded... +41ms
[2024-07-26T10:52:01.109] [INFO ] [TSED] - Mount app context +0ms
[2024-07-26T10:52:01.110] [INFO ] [TSED] - Load routes +1ms
[2024-07-26T10:52:01.138] [ERROR] [TSED] - TypeError: Cannot read properties of undefined (reading 'paramType')
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:85:52
    at Array.findIndex (<anonymous>)
    at PlatformHandlerMetadata.hasParamType (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:85:33)
    at new PlatformHandlerMetadata (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:23:41)
    at PlatformHandlerMetadata.from (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:59:20)
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouter.js:57:48
    at Array.map (<anonymous>)
    at PlatformRouter.addRoute (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouter.js:56:32)
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouters.js:79:20

### To Reproduce

Debugger listening on ws://127.0.0.1:9229/d3f2fed7-a36d-4e6d-8466-8552e2bee8a2
For help, see: https://nodejs.org/en/docs/inspector
[2024-07-26T10:52:00.964] [DEBUG] [TSED] - Start server...
[2024-07-26T10:52:00.982] [INFO ] [TSED] - Loading EXPRESS platform adapter... +15ms
[2024-07-26T10:52:01.067] [INFO ] [TSED] - Injector created... +85ms
[2024-07-26T10:52:01.068] [INFO ] [TSED] - Build providers +1ms
[2024-07-26T10:52:01.109] [INFO ] [TSED] - Settings and injector loaded... +41ms
[2024-07-26T10:52:01.109] [INFO ] [TSED] - Mount app context +0ms
[2024-07-26T10:52:01.110] [INFO ] [TSED] - Load routes +1ms
[2024-07-26T10:52:01.138] [ERROR] [TSED] - TypeError: Cannot read properties of undefined (reading 'paramType')
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:85:52
    at Array.findIndex (<anonymous>)
    at PlatformHandlerMetadata.hasParamType (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:85:33)
    at new PlatformHandlerMetadata (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:23:41)
    at PlatformHandlerMetadata.from (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:59:20)
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouter.js:57:48
    at Array.map (<anonymous>)
    at PlatformRouter.addRoute (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouter.js:56:32)
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouters.js:79:20
    at Array.forEach (<anonymous>)

### Expected behavior

Debugger listening on ws://127.0.0.1:9229/d3f2fed7-a36d-4e6d-8466-8552e2bee8a2
For help, see: https://nodejs.org/en/docs/inspector
[2024-07-26T10:52:00.964] [DEBUG] [TSED] - Start server...
[2024-07-26T10:52:00.982] [INFO ] [TSED] - Loading EXPRESS platform adapter... +15ms
[2024-07-26T10:52:01.067] [INFO ] [TSED] - Injector created... +85ms
[2024-07-26T10:52:01.068] [INFO ] [TSED] - Build providers +1ms
[2024-07-26T10:52:01.109] [INFO ] [TSED] - Settings and injector loaded... +41ms
[2024-07-26T10:52:01.109] [INFO ] [TSED] - Mount app context +0ms
[2024-07-26T10:52:01.110] [INFO ] [TSED] - Load routes +1ms
[2024-07-26T10:52:01.138] [ERROR] [TSED] - TypeError: Cannot read properties of undefined (reading 'paramType')
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:85:52
    at Array.findIndex (<anonymous>)
    at PlatformHandlerMetadata.hasParamType (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:85:33)
    at new PlatformHandlerMetadata (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:23:41)
    at PlatformHandlerMetadata.from (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformHandlerMetadata.js:59:20)
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouter.js:57:48
    at Array.map (<anonymous>)
    at PlatformRouter.addRoute (file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouter.js:56:32)
    at file:///home/wada/code/testcenter-api/node_modules/@tsed/platform-router/lib/esm/domain/PlatformRouters.js:79:20
    at Array.forEach (<anonymous>)

### OS

linux

### Node version

node: v20.15.1

### Library version

npm: v10.7.0

**Comment by Romakita** [comment]
Hello @KarthikeyanPriyaGuhanMahi 
Please create a reproducible repository using `tsed init .`. Your logs aren't enough to start investigation and show something custom from your project. Please take a time to reproduce the bug using official CLI.

See you
