### ISSUE TITLE
[BUG] jest tests fail starting from 7.80.0

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2810]
### Describe the bug

After updating from `7.79.4` to `7.80.0` my jest tests start failing with the following reason:

```
Test suite failed to run

    TypeError: A dynamic import callback was invoked without --experimental-vm-modules

      4 |
      5 | beforeAll(async () => {
    > 6 |   await PlatformTest.bootstrap(Server)();
        |                                       ^
      7 |   global.injector = PlatformTest.injector;
      8 | });
      9 |

      at new PlatformExpress (../../node_modules/@tsed/platform-express/src/components/PlatformExpress.ts:75:5)
      at construct (../../node_modules/@tsed/di/src/common/services/InjectorService.ts:751:46)
      at InjectorService.resolve (../../node_modules/@tsed/di/src/common/services/InjectorService.ts:639:18)
      at InjectorService.invoke (../../node_modules/@tsed/di/src/common/services/InjectorService.ts:223:21)
      at createInjector (../../node_modules/@tsed/common/src/utils/createInjector.ts:41:12)
      at new PlatformBuilder (../../node_modules/@tsed/common/src/builder/PlatformBuilder.ts:47:36)
      at Function.build (../../node_modules/@tsed/common/src/builder/PlatformBuilder.ts:122:12)
      at before (../../node_modules/@tsed/common/src/services/PlatformTest.ts:65:40)
      at Object.<anonymous> (src/test/scripts/setup-after-env.ts:6:39)
```

The `beforeAll` code is from a `setupAfterEnv` jest script.

Everything works fine in `7.79.4`. 

### To Reproduce

Let me know if you need help to reproduce

### Expected behavior

To not fail 😃 Should work as in `7.79.4`

### OS

macOS

### Node version

20.12.2

### Library version

7.80.0

**Comment by Romakita** [comment]
@EinfachHans install the last version. It’s fixed ;)

**Comment by EinfachHans** [comment]
@Romakita sorry i forget to mention, i already tested with the latest version `7.82.1`

**Comment by Romakita** [comment]
Hum. ok maybe I have to rollback also the tsconfig of DI package.

**Comment by Romakita** [comment]
Ha shit, it's the PlatformExpress. Ok I'll fix that

**Comment by Romakita** [comment]
@EinfachHans 7.82.2 should fix issue :)
