### ISSUE TITLE
[BUG] tsInstance.getOriginalSourceFile is not a function Error with ts-node-dev

### ISSUE THREAD

**Issue by raphaelvserafim** [TypedProject/ts-express-decorators#2840]
### Describe the bug

I am encountering a compilation error when running my project using ts-node-dev. The error message indicates that the function tsInstance.getOriginalSourceFile is not recognized.

### To Reproduce

ts-node-dev version: 2.0.0
ts-node version: 10.9.2
TypeScript version: 5.6.2

### Expected behavior

```js
[INFO] 09:55:10 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.2, typescript ver. 5.6.2)
Debugger listening on ws://127.0.0.1:54994/379c9c6f-d4ba-4d00-9f58-15a2b0c75a85
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Compilation error in /Users/raphael/Documents/Job/Rubens/extrahomework-backend/src/database/Synchronize.ts
Error: tsInstance.getOriginalSourceFile is not a function
    at Object.<anonymous> (/Users/raphael/Documents/Job/Rubens/extrahomework-backend/src/database/Synchronize.ts:1:7)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._compile (/Users/raphael/Documents/Job/Rubens/extrahomework-backend/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/_s/52l92khj17s7ykfm2v1mm13c0000gn/T/ts-node-dev-hook-39731299528761044.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/_s/52l92khj17s7ykfm2v1mm13c0000gn/T/ts-node-dev-hook-39731299528761044.js:114:20)
    at require.extensions.<computed> (/private/var/folders/_s/52l92khj17s7ykfm2v1mm13c0000gn/T/ts-node-dev-hook-39731299528761044.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/raphael/Documents/Job/Rubens/extrahomework-backend/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)


### Code snippets

_No response_

### Repository URL example

_No response_

### OS

macOS

### Node version

v20.8.1

### Library version

7.83.1

### Additional context

_No response_

**Comment by Romakita** [comment]
@raphaelvserafim isn’t a tsed issue. Please open issue on ts-node-dev repository.

see you
