### ISSUE TITLE
Endpoint testing "ServerLoader cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by oehm-smith** [TypedProject/ts-express-decorators#531]
## Information

- **Version:** 5.6.0
- **Type:** Issue

## Description
Following https://tsed.io/docs/testing.html#test-your-rest-api.  Test fails to start.  The error is as follows.  It is a similar error to https://github.com/TypedProject/ts-express-decorators/issues/229.

```
10:58 $ ./node_modules/mocha/bin/mocha -r ts-node/register server/src/controllers/HelloController.spec.ts

/Users/bbos/dev/dhs/translate/translation-dict/server/src/Server.js:31
        return _super !== null && _super.apply(this, arguments) || this;
                                         ^
TypeError: Class constructor ServerLoader cannot be invoked without 'new'
    at new Server (/Users/bbos/dev/dhs/translate/translation-dict/server/src/Server.js:31:42)
    at Object.<anonymous> (/Users/bbos/dev/dhs/translate/translation-dict/server/src/Server.js:64:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/bbos/dev/dhs/translate/translation-dict/server/src/controllers/HelloController.spec.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/Users/bbos/dev/dhs/translate/translation-dict/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/bbos/dev/dhs/translate/translation-dict/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/bbos/dev/dhs/translate/translation-dict/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/bbos/dev/dhs/translate/translation-dict/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/bbos/dev/dhs/translate/translation-dict/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/bbos/dev/dhs/translate/translation-dict/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

## Example

The transpile never gets past
```
...
import {Server} from "../Server";

```
The `tsconfig.json` is:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": ["reflect-metadata", "node", "mocha"],
    "lib": [
      "es2015",
      "dom"
    ],
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules"
  ]
}

```

## Acceptance criteria

The test runs.

**Comment by Romakita** [comment]
@alexproca But your project works when you run your server with ts-node or directly with node ?

**Comment by oehm-smith** [comment]
Thanks for the prompt @Romakita .  How silly of me, I didn't see that there was also a `server.js` as well as the expected `server.ts`.  That `.js` seems to have been transpilled incorrectly (perhaps prior to setting the `tsconfig.json target` to `es2015` (or greater)).  Once the js file was removed it worked.  Cheers!
