### ISSUE TITLE
ConverterService Injection Error since moving to 5.21

### ISSUE THREAD

**Issue by DrGanmon** [TypedProject/ts-express-decorators#580]
## Information

- **Version:** 5.21.0
- **Type:** Issue

## Description
Since update the upgrade from 2.4.4 ( I know its a long time) i had issues with the ConverterService Injection. Or rather to say i cant start my Project anymore. Maybe i miss the Forest from the trees, but for now i realy have no idea whats going on.

Ps. Moving back to 2.4.4 resolves the issue immediately. 

## Example

```
[2019-07-02T15:52:14.812] [INFO ] [TSED] - Build services
{ INJECTION_ERROR: Injection failed on ConverterService
Origin: Cannot read property 'get' of undefined
    at Map._invoke (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:432:13)
    at Map.invoke (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:174:50)
    at Map.<anonymous> (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:214:14)
    at Generator.next (<anonymous>)
    at ~/projectDir/node_modules/@tsed/di/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (~/projectDir/node_modules/@tsed/di/node_modules/tslib/tslib.js:106:16)
    at Map.load (~/projectDir/node_modules/@tsed/di/lib/services/InjectorService.js:160:24)
    at Server.<anonymous> (~/projectDir/node_modules/@tsed/common/src/server/components/ServerLoader.ts:440:25)
    at Generator.next (<anonymous>)
    at fulfilled (~/projectDir/node_modules/@tsed/common/node_modules/tslib/tslib.js:107:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  name: 'INJECTION_ERROR',
  tokens: [ [Function: ConverterService] ],
  origin:
   TypeError: Cannot read property 'get' of undefined
       at new ConverterService (~/projectDir/node_modules/@tsed/common/src/converters/services/ConverterService.ts:18:49)
       at construct (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:478:48)
       at Map._invoke (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:430:18)
       at Map.invoke (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:174:50)
       at Map.<anonymous> (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:214:14)
       at Generator.next (<anonymous>)
       at ~/projectDir/node_modules/@tsed/di/node_modules/tslib/tslib.js:110:75
       at new Promise (<anonymous>)
       at Object.__awaiter (~/projectDir/node_modules/@tsed/di/node_modules/tslib/tslib.js:106:16)
       at Map.load (~/projectDir/node_modules/@tsed/di/lib/services/InjectorService.js:160:24)
       at Server.<anonymous> (~/projectDir/node_modules/@tsed/common/src/server/components/ServerLoader.ts:440:25)
       at Generator.next (<anonymous>)
       at fulfilled (~/projectDir/node_modules/@tsed/common/node_modules/tslib/tslib.js:107:62)
       at process._tickCallback (internal/process/next_tick.js:68:7)
       at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
       at startup (internal/bootstrap/node.js:283:19)
       at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) }
(node:24595) UnhandledPromiseRejectionWarning: INJECTION_ERROR: Injection failed on ConverterService
Origin: Cannot read property 'get' of undefined
    at Map._invoke (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:432:13)
    at Map.invoke (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:174:50)
    at Map.<anonymous> (~/projectDir/node_modules/@tsed/di/src/services/InjectorService.ts:214:14)
    at Generator.next (<anonymous>)
    at ~/projectDir/node_modules/@tsed/di/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (~/projectDir/node_modules/@tsed/di/node_modules/tslib/tslib.js:106:16)
    at Map.load (~/projectDir/node_modules/@tsed/di/lib/services/InjectorService.js:160:24)
    at Server.<anonymous> (~/projectDir/node_modules/@tsed/common/src/server/components/ServerLoader.ts:440:25)
    at Generator.next (<anonymous>)
    at fulfilled (~/projectDir/node_modules/@tsed/common/node_modules/tslib/tslib.js:107:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:24595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:24595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Romakita** [comment]
Hello @DrGanmon 
Can you send me your package.json and your server configuration please ?
If you can give an access to your repository, I can take a look also :)

See you

**Comment by DrGanmon** [comment]
Hello @Romakita 
I Invited you to the repo.

Thanks for the Help so far :)

**Comment by Romakita** [comment]
Ok I found your issue. The problem come from reflect-metadata installed on project level and the reflect-metadata embded by tsed.

I pushed the fix directly on your repo :)
Run npm i and npm dedup
See you

**Comment by DrGanmon** [comment]
Thanks a lot, you saved me :) 
is there any reason wy you `"sequelize-typescript": "^1.0.0-beta.3"` replaced with `"sequelize-typescript": "0.6.11"`?

**Comment by Romakita** [comment]
I’d just forgot to rollback this change. You can revert it ;)

**Comment by DrGanmon** [comment]
ok :) 
it works perfectly :)

**Comment by DrGanmon** [comment]
p.s. I owe you a beer

**Comment by Romakita** [comment]
héhé ;)
