### ISSUE TITLE
Swagger could not init when using bodyparams without args

### ISSUE THREAD

**Issue by imsuwj** [TypedProject/ts-express-decorators#643]
## Information

- **Version:** 5.31.0
- **Type:** Issue

## Description

when using `BodyParams` without args, swagger could not init

Change class PayLoad to any, same.

And disable the swagger feature, the code works well.

## Example

```
import {Post, BodyParams, Controller, Property} from "@tsed/common";
class PayLoad {
  @Property()
  attr: string;
}

@Controller("/test")
class TestCtrl {
  @Post("/")
  public test(
    @BodyParams() payload: PayLoad
  ) {
    console.log(payload)
  }
}
```

```
[2019-09-14T18:32:12.114] [ERROR] [app] - Server encounter an error => undefined
[2019-09-14T18:32:12.114] [ERROR] [app] - TypeError: Cannot read property 'prototype' of undefined
    at getClass (/path/to/node_modules/@tsed/core/src/utils/ObjectUtils.ts:39:17)
    at Object.ancestorsOf (/path/to/node_modules/@tsed/core/src/utils/ObjectUtils.ts:264:23)
    at Function.getProperties (/path/to/node_modules/@tsed/common/src/jsonschema/registries/PropertyRegistry.ts:31:5)
    at OpenApiModelSchemaBuilder.build (/path/to/node_modules/@tsed/swagger/src/class/OpenApiModelSchemaBuilder.ts:23:41)
    at OpenApiParamsBuilder.getInBodyParam (/path/to/node_modules/@tsed/swagger/src/class/OpenApiParamsBuilder.ts:161:15)
    at OpenApiParamsBuilder.build (/path/to/node_modules/@tsed/swagger/src/class/OpenApiParamsBuilder.ts:53:55)
    at utils_1.parseSwaggerPath.forEach (/path/to/node_modules/@tsed/swagger/src/class/OpenApiEndpointBuilder.ts:37:117)
    at Array.forEach (<anonymous>)
    at OpenApiEndpointBuilder.build (/path/to/node_modules/@tsed/swagger/src/class/OpenApiEndpointBuilder.ts:36:62)
    at endpoint.pathsMethods.forEach.pathMethod (/path/to/node_modules/@tsed/swagger/src/services/SwaggerService.ts:144:105)
(node:33507) DeprecationWarning: $onServerInitError hook is deprecated. Hook will be removed
```

## Acceptance criteria

- [ ] Criteria 1

**Comment by imsuwj** [comment]
swagger options: 
```
config.swagger = {
      path: '/api-docs'
    };
```

**Comment by Romakita** [comment]
Can you send me you tsconfig please :)

**Comment by imsuwj** [comment]
@Romakita 
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["src/**/*"],
  "exclude": ["dist", "node_modules"]
}

```

**Comment by imsuwj** [comment]
Code below works well.
```
BodyParmas("attr") attr: string
```

**Comment by Romakita** [comment]
Add "emitDecoratorMetadata": true 
It's a common problem. Dev forgot to add this line. 
On website this is one of the warning XD

```
WARNING

Ts.ED requires Node >= 8, Express >= 4, TypeScript >= 2.0 and the experimentalDecorators, emitDecoratorMetadata, types and lib compilation options in your tsconfig.json file.
```

See you

**Comment by imsuwj** [comment]
@Romakita solved. thanks.
