### ISSUE TITLE
@tsed/mongoose - OverwriteModelError: Cannot overwrite `User` model once compiled.

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/ts-express-decorators#701]
Version: 5.32.1

After enough server restarts, I'm getting OverwriteModelError for an existing mongoose model which worked before. I'm still trying to understand why.

It already happened to me before with a different model, and it was fixed once I renamed it with a model name that hasn't been used before.

I'm really struggling to understand what's going on.

The name "User" is unique both as a mongoose model and as a class name within the app in general.

**schemas/user/User.ts**
```
import { Property } from '@tsed/common';
import { Model, ObjectID } from '@tsed/mongoose';

import SubSchema from './SubSchema';

@Model()
export default class User {

  @ObjectID('id')
  _id: string;

  @ObjectID()
  app_id: string;

  @Property()
  email: string;

  @Property()
  name: string;

  @Property()
  subSchema: SubSchema;

}
```

Error:

```
 { OverwriteModelError: Cannot overwrite `User` model once compiled.
    at new OverwriteModelError (D:\Projects\matchmakingApp\server\node_modules\mongoose\lib\error\overwriteModel.js:20:11)
    at Mongoose.model (D:\Projects\matchmakingApp\server\node_modules\mongoose\lib\index.js:517:13)
    at Object.createModel (D:\Projects\matchmakingApp\server\node_modules\@tsed\mongoose\src\utils\createModel.ts:25:19)
    at Model (D:\Projects\matchmakingApp\server\node_modules\@tsed\mongoose\src\decorators\model.ts:45:27)
    at DecorateConstructor (D:\Projects\matchmakingApp\server\node_modules\reflect-metadata\Reflect.js:541:33)
    at Object.decorate (D:\Projects\matchmakingApp\server\node_modules\reflect-metadata\Reflect.js:130:24)
    at __decorate (D:\Projects\matchmakingApp\server\build\models\schemas\user\User.js:4:92)
    at Object.<anonymous> (D:\Projects\matchmakingApp\server\build\models\schemas\user\User.js:76:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\Projects\matchmakingApp\server\build\services\UserService.js:26:32)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
  message: 'Cannot overwrite `User` model once compiled.',
  name: 'OverwriteModelError' }
```

**Comment by Romakita** [comment]
Hello @royibernthal 

On stackoverflow I saw that:
```
So Another Reason why You might get this Error is if you use the same model in different files but your require path has a different case. For example in my situation I had:

require('./models/User') in one file and then in another file where I needed access to the User model I had require('./models/user').

I guess the look up for modules & mongoose is treating it as a different file. Once I made sure the case matched in both it was no longer an issue.
```

Can you check if you this problem ;) 

See you
Romain

**Comment by Romakita** [comment]
https://stackoverflow.com/questions/19051041/cannot-overwrite-model-once-compiled-mongoose

**Comment by royibernthal** [comment]
Hi @Romakita 

The file name is using the exact same case in all of the imports.

As for
https://stackoverflow.com/questions/19051041/cannot-overwrite-model-once-compiled-mongoose

Is there any way I could be instantiating the same schema more than once? If I understand correctly, the instantiation is done by tsed under the hood, I'm simply injecting what's supposed to be a single instance.


The odd thing is, if I do a rename refactor for that model, to a name that wasn't used before, it works as expected.
On the other hand, if I refactor using a name that I used before, I get the same error. It's as if things are cached somewhere somehow.

**Comment by Romakita** [comment]
Do you have a link where I can checkout your project ?

**Comment by royibernthal** [comment]
Sure, I omitted some auth stuff since this repo is public, but it's more or less complete:
https://github.com/royibernthal/matchmaking-server

**Comment by Romakita** [comment]
@royibernthal I haven't error on https://github.com/royibernthal/matchmaking-server

**Comment by royibernthal** [comment]
@Romakita That's the point. It works in the beginning in a clean env, but I'm starting to get that error after the server has been restarted enough times (or so it seems). See what I wrote above about renaming and possible cache - if that makes sense.

**Comment by Romakita** [comment]
@royibernthal Do you use our given command to start project ?

```
{
  "scripts": {
     "start": "nodemon --watch 'src/**/*.ts' --ignore 'node_modules/**/*' --exec ts-node src/index.ts"
  }
}
```

It should fix your problem in dev mode ;)

**Comment by royibernthal** [comment]
@Romakita Bingo :) That was the issue. I noticed it now in the optional package.json in getting started doc.

1) Maybe it should be emphasized more somewhere? Or is it emphasized in another place I missed?
2) I had to remove the single quotes for it to work for me. Does it work with the quotes for you? If no, maybe the example should be updated?
`nodemon --watch src/**/*.ts --ignore node_modules/**/* --exec ts-node src/index.ts`
3) How did using that command solve the issue? What I did before was compile ts manually and have nodemon watch the build dir.
4) Will I not encounter the same issue in prod?

**Comment by Romakita** [comment]
1. Yes I'll change de documentation ;)
2. It depend on your Os. I'm on mac/linux and it works for me. Without single quote it works also. I'll update all example ;)
3. Hum an intuition ^^. Watching file built by tsc generate always issue (one of my contributors already ask me about that) due to Os filesystem, disk latency and deamon restart your app faster than the code is compiled. So this is what, I use a tsconfig with `noEmit: true` in dev mode to avoid filesystem issue (and  reach performance). I remove noEmit options when I build the source in production mode and run PM2 or node process over generated files.
4. Certainly not ^^

See you
Romain

**Comment by royibernthal** [comment]
Got it. Thanks a lot for the help and the explanations :)
