### ISSUE TITLE
Testing not working

### ISSUE THREAD

**Issue by ziofat** [TypedProject/ts-express-decorators#717]
## Information

- **Version:** 5.34.9
- **Type:** Issue

## Description
Run npm test failed with timeout error.

I have exactly same `scripts/mocha/register.js` and `test/mocha.opts` with sample project.

My test case are shown below.

## Example

```ts
import { ExpressApplication } from '@tsed/common';
import { TestContext } from '@tsed/testing';
import { expect } from 'chai';
import SuperTest from 'supertest';
// In sample it is import * as SuperTest from 'supertest'
// but in my workspace it will throw an error:
// Type 'typeof supertest' has no call signatures
import { Server } from '../../../src/Server';

describe('Equip', () => {
    let request: SuperTest.SuperTest<SuperTest.Test>;
    // bootstrap your expressApplication in first
    before(TestContext.bootstrap(Server));
    before(TestContext.inject([ExpressApplication], (expressApplication: ExpressApplication) => {
        request = SuperTest(expressApplication);
    }));
    after(TestContext.reset);

    // then run your test
    describe('GET /rest/equip', () => {
        it('should return all equip', async () => {
            const response = await request.get('/rest/equip').expect(200);

            expect(response.body.data).to.be.an('array');
        });
    });
});


```
Failed with following message:

> "before all" hook: before in "Equip":
> Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

## Acceptance criteria

- [x] Test should pass

**Comment by ziofat** [comment]
My previous ServerSettings looks like this:
```ts
@ServerSettings({
    rootDir,
    acceptMimes: ['application/json'],
    mount: {
        '/api': '${rootDir}/controllers/**/*.{ts,js}',
    },
    componentsScan: [
        '${rootDir}/middlewares/**/*.{ts,js}',
        '${rootDir}/services/**/*.{ts,js}',
    ],
    typeorm: [
        {
            name: 'resources',
            type: 'mysql',
            host: process.env.MYSQL_DB_HOST,
            port: +process.env.MYSQL_DB_PORT,
            synchronize: true,
            username: process.env.MYSQL_DB_USER,
            password: process.env.MYSQL_DB_PASS,
            database: process.env.MYSQL_DB_NAME,
            entities: [
                `${__dirname}/entities/*.{ts,js}`,
            ],
        },
    ],
    swagger: [
        {
            path: '/api-docs',
        },
    ],
    logger: {
        reqIdBuilder: generateReqId,
        logRequest: false,
        level: process.env.LOG_LEVEL as ('debug' | 'info' | 'warn' | 'error' | 'off'),
    },
})
```

After I changed it to this: 
```ts
    mount: {
        '/api': [
            EquipCtrl,
            // '${rootDir}/controllers/**/*.{ts,js}',
        ],
    },
    componentsScan: [
        // '${rootDir}/middlewares/**/*.{ts,js}',
        '${rootDir}/services/**/*.{ts,js}',
    ],
```

I got a different error:
```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["errors"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at ServerResponse.header (/data/workspace/j3pz-server/node_modules/express/lib/response.js:771:10)
    at GlobalErrorHandlerMiddleware.setHeaders (/data/workspace/j3pz-server/node_modules/@tsed/common/src/server/components/GlobalErrorHandlerMiddleware.ts:72:16)
    at GlobalErrorHandlerMiddleware.use (/data/workspace/j3pz-server/node_modules/@tsed/common/src/server/components/GlobalErrorHandlerMiddleware.ts:27:12)
    at HandlerBuilder.invoke (/data/workspace/j3pz-server/node_modules/@tsed/common/src/mvc/builders/HandlerBuilder.ts:208:23)
    at SafeSubscriber.rxjs_1.zip.pipe.subscribe.context [as _next] (/data/workspace/j3pz-server/node_modules/@tsed/common/src/mvc/builders/HandlerBuilder.ts:182:34)
    at SafeSubscriber.__tryOrUnsub (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:265:10)
    at SafeSubscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:207:14)
    at Subscriber._next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:139:22)
    at Subscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at ZipSubscriber.checkIterators (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/observable/zip.ts:197:19)
    at ZipBufferIterator.notifyNext (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/observable/zip.ts:324:17)
    at InnerSubscriber._next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at InnerSubscriber._next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at CatchSubscriber.Subscriber._next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:139:22)
    at CatchSubscriber.Subscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Observable._subscribe (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
    at Observable._trySubscribe (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Observable.ts:238:19)
    at Observable.subscribe (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Observable.ts:219:14)
    at MapOperator.call (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/operators/map.ts:59:19)
    at Observable.subscribe (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Observable.ts:214:25)
    at CatchOperator.call (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/operators/catchError.ts:107:19)
    at Observable.subscribe (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Observable.ts:214:25)
    at Object.subscribeToResult (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/util/subscribeToResult.ts:26:19)
    at SwitchMapSubscriber._innerSub (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/operators/switchMap.ts:139:30)
    at SwitchMapSubscriber._next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/operators/switchMap.ts:128:10)
    at SwitchMapSubscriber.Subscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Subject.next (/data/workspace/j3pz-server/node_modules/rxjs/src/internal/Subject.ts:70:17)
    at sources.forEach.source (/data/workspace/j3pz-server/node_modules/@tsed/common/src/mvc/builders/HandlerBuilder.ts:189:16)
    at Array.forEach (<anonymous>)
    at /data/workspace/j3pz-server/node_modules/@tsed/common/src/mvc/builders/HandlerBuilder.ts:188:15
    at /data/workspace/j3pz-server/node_modules/@tsed/common/src/mvc/builders/HandlerBuilder.ts:138:9
    at Layer.handle_error (/data/workspace/j3pz-server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/data/workspace/j3pz-server/node_modules/express/lib/router/index.js:315:13)
    at /data/workspace/j3pz-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/data/workspace/j3pz-server/node_modules/express/lib/router/index.js:335:12)
    at next (/data/workspace/j3pz-server/node_modules/express/lib/router/index.js:275:10)
    at /data/workspace/j3pz-server/node_modules/express/lib/router/index.js:635:15
    at next (/data/workspace/j3pz-server/node_modules/express/lib/router/index.js:260:14)
    at next (/data/workspace/j3pz-server/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle_error (/data/workspace/j3pz-server/node_modules/express/lib/router/layer.js:67:12)
    at next (/data/workspace/j3pz-server/node_modules/express/lib/router/route.js:135:13)
    at /data/workspace/j3pz-server/node_modules/@tsed/common/src/mvc/builders/HandlerBuilder.ts:271:14
    at done (/data/workspace/j3pz-server/node_modules/@tsed/common/src/mvc/builders/HandlerBuilder.ts:84:16)
    at process.then.catch (/data/workspace/j3pz-server/node_modules/@tsed/common/src/mvc/builders/HandlerBuilder.ts:115:98)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

However, using 'npm start' to boot the server all things are correct.

**Comment by ziofat** [comment]
Well, resolved it by increasing the timeout...
